package ua.ihromant.sod;

public enum Creature {
    PIKEMAN, HALBERDIER, ARCHER, MARKSMAN, GRIFFIN, ROYAL_GRIFFIN, SWORDSMAN, CRUSADER, MONK, ZEALOT, CAVALIER, CHAMPION, ANGEL, ARCHANGEL,
    CENTAUR, CENTAUR_CAPTAIN, DWARF, BATTLE_DWARF, WOOD_ELF, GRAND_ELF, PEGASUS, SILVER_PEGASUS, DENDROID_GUARD, DENDROID_SOLDIER, UNICORN, WAR_UNICORN, GREEN_DRAGON, GOLD_DRAGON,
    GREMLIN, MASTER_GREMLIN, STONE_GARGOYLE, OBSIDIAN_GARGOYLE, STONE_GOLEM, IRON_GOLEM, MAGE, ARCH_MAGE, GENIE, MASTER_GENIE, NAGA, NAGA_QUEEN, GIANT, TITAN,
    IMP, FAMILIAR, GOG, MAGOG, HELL_HOUND, CERBERUS, DEMON, HORNED_DEMON, PIT_FIEND, PIT_LORD, EFREET, EFREET_SULTAN, DEVIL, ARCH_DEVIL,
    SKELETON, SKELETON_WARRIOR, WALKING_DEAD, ZOMBIE, WIGHT, WRAITH, VAMPIRE, VAMPIRE_LORD, LICH, POWER_LICH, BLACK_KNIGHT, DREAD_KNIGHT, BONE_DRAGON, GHOST_DRAGON,
    TROGLODYTE, INFERNAL_TROGLODYTE, HARPY, HARPY_HAG, BEHOLDER, EVIL_EYE, MEDUSA, MEDUSA_QUEEN, MINOTAUR, MINOTAUR_KING, MANTICORE, SCORPICORE, RED_DRAGON, BLACK_DRAGON,
    GOBLIN, HOBGOBLIN, WOLF_RIDER, WOLF_RAIDER, ORC, ORC_CHIEFTAIN, OGRE, OGRE_MAGE, ROC, THUNDERBIRD, CYCLOPS, CYCLOPS_KING, BEHEMOTH, ANCIENT_BEHEMOTH,
    GNOLL, GNOLL_MARAUDER, LIZARDMAN, LIZARD_WARRIOR, SERPENT_FLY, DRAGON_FLY, BASILISK, GREATER_BASILISK, GORGON, MIGHTY_GORGON, WYVERN, WYVERN_MONARCH, HYDRA, CHAOS_HYDRA,
    PIXIE, SPRITE, AIR_ELEMENTAL, STORM_ELEMENTAL, WATER_ELEMENTAL, ICE_ELEMENTAL, FIRE_ELEMENTAL, ENERGY_ELEMENTAL, EARTH_ELEMENTAL, MAGMA_ELEMENTAL, PSYCHIC_ELEMENTAL, MAGIC_ELEMENTAL, FIREBIRD, PHOENIX,
    PEASANT, HALFLING, ROGUE, BOAR, NOMAD, MUMMY, SHARPSHOOTER, TROLL, GOLD_GOLEM, DIAMOND_GOLEM, ENCHANTER, FAERIE_DRAGON, RUST_DRAGON, CRYSTAL_DRAGON, AZURE_DRAGON
}
