package ua.ihromant.sod;

public enum HeroType {
    KNIGHT, CLERIC,
    RANGER, DRUID,
    ALCHEMIST, WIZARD,
    DEMONIAC, HERETIC,
    DEATH_KNIGHT, NECROMANCER,
    OVERLORD, WARLOCK,
    BARBARIAN, BATTLE_MAGE,
    BEASTMASTER, WITCH,
    PLANESWALKER, ELEMENTALIST
}
