package ua.ihromant.sod;

public enum Spell {
    MAGIC_ARROW, HASTE, BLOODLUST, PROTECTION_FROM_FIRE, CURSE, BLESS, PROTECTION_FROM_WATER, CURE, DISPEL, STONE_SKIN, SLOW, SHIELD,
    VIEW_AIR, SUMMON_BOAT, VIEW_EARTH,
    LIGHTNING_BOLT, PRECISION, PROTECTION_FROM_AIR, DISRUPTING_RAY, FORTUNE, FIRE_WALL, BLIND, ICE_BOLT, REMOVE_OBSTACLE, WEAKNESS, QUICKSAND, DEATH_RIPPLE,
    VISIONS, DISGUISE, SCUTTLE_BOAT,
    HYPNOTIZE, DESTROY_UNDEAD, AIR_SHIELD, FIREBALL, LAND_MINES, MISFORTUNE, FORGETFULNESS, FROST_RING, MIRTH, TELEPORT, ANTIMAGIC, PROTECTION_FROM_EARTH, EARTHQUAKE, ANIMATE_DEAD, FORCE_FIELD,
    COUNTERSTRIKE, CHAIN_LIGHTNING, INFERNO, ARMAGEDDON, FRENZY, BERSERK, SLAYER, FIRE_SHIELD, CLONE, PRAYER, RESURRECTION, METEOR_SHOWER, SORROW,
    WATER_WALK, TOWN_PORTAL,
    TITANS_LIGHTNING_BOLT, MAGIC_MIRROR, AIR_ELEMENTAL, FIRE_ELEMENTAL, SACRIFICE, WATER_ELEMENTAL, IMPLOSION, EARTH_ELEMENTAL,
    FLY, DIMENSION_DOOR,
}
