CREATE TABLE artifact (
	id serial primary key,
	full_name varchar not null,
	slot int4 not null,
	artifact_type int4 not null,
	gold_cost int4 not null,
	combo_id int4
);

--drop table public.artifact;

insert into artifact (
full_name, slot, artifact_type, gold_cost, combo_id
) values
('CLOAK_OF_THE_UNDEAD_KING',1,4,12000,null),
('ADMIRALS_HAT',0,4,25000,null),
('WIZARDS_WELL',8,4,3000,null),
('ELIXIR_OF_LIFE',8,4,20000,null),
('BOW_OF_THE_SHARPSHOOTER',8,4,12000,null),
('CORNUCOPIA',8,4,20000,null),
('STATUE_OF_LEGION',8,4,25000,null),
('TITANS_THUNDER',3,4,40000,null),
('ANGELIC_ALLIANCE',3,4,84000,null),
('RING_OF_THE_MAGI',6,4,3000,null),
('ARMOR_OF_THE_DAMNED',5,4,12000,null),
('POWER_OF_THE_DRAGON_FATHER',5,4,42000,null),
('CAPE_OF_CONJURING',1,0,1500,(SELECT id FROM artifact WHERE full_name = 'RING_OF_THE_MAGI')),
('DRAGON_WING_TABARD',1,1,4000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('VAMPIRES_COWL',1,1,4000,(SELECT id FROM artifact WHERE full_name = 'CLOAK_OF_THE_UNDEAD_KING')),
('SURCOAT_OF_COUNTERPOISE',1,2,4000,null),
('AMBASSADORS_SASH',1,2,5000,null),
('EVERFLOWING_CRYSTAL_CLOAK',1,2,5000,(SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA')),
('RECANTERS_CLOAK',1,2,8000,null),
('CAPE_OF_VELOCITY',1,2,10000,null),
('ANGEL_WINGS',1,3,20000,null),
('DRAGONBONE_GREAVES',7,0,2000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('BOOTS_OF_SPEED',7,1,6000,null),
('DEAD_MANS_BOOTS',7,2,6000,(SELECT id FROM artifact WHERE full_name = 'CLOAK_OF_THE_UNDEAD_KING')),
('BOOTS_OF_POLARITY',7,3,6000,null),
('SANDALS_OF_THE_SAINT',7,3,8000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('BOOTS_OF_LEVITATION',7,3,10000,null),
('HELM_OF_THE_ALABASTER_UNICORN',0,0,1000,null),
('SKULL_HELMET',0,0,3000,(SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED')),
('HELM_OF_CHAOS',0,1,4000,null),
('CROWN_OF_THE_SUPREME_MAGI',0,1,5000,null),
('HELLSTORM_HELMET',0,2,6000,null),
('CROWN_OF_DRAGONTOOTH',0,3,8000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('THUNDER_HELMET',0,3,10000,(SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER')),
('SEA_CAPTAINS_HAT',0,3,15000,(SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT')),
('HELM_OF_HEAVENLY_ENLIGHTENMENT',0,3,24000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('SPELLBINDERS_HAT',0,3,30000,null),
('SHIELD_OF_THE_DWARVEN_LORDS',4,0,2000,null),
('SHIELD_OF_THE_YAWNING_DEAD',4,1,3000,(SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED')),
('BUCKLER_OF_THE_GNOLL_KING',4,1,4000,null),
('TARG_OF_THE_RAMPAGING_OGRE',4,2,5000,null),
('SHIELD_OF_THE_DAMNED',4,2,6000,(SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE_(CAMPAIGN_ONLY)')),
('DRAGON_SCALE_SHIELD',4,2,6000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('LIONS_SHIELD_OF_COURAGE',4,3,16000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('SENTINELS_SHIELD',4,3,10000,(SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER')),
('CHARM_OF_MANA',8,0,500,(SELECT id FROM artifact WHERE full_name = 'WIZARDS_WELL')),
('TALISMAN_OF_MANA',8,0,1000,(SELECT id FROM artifact WHERE full_name = 'WIZARDS_WELL')),
('MYSTIC_ORB_OF_MANA',8,0,1500,(SELECT id FROM artifact WHERE full_name = 'WIZARDS_WELL')),
('ORB_OF_SILT',8,2,6000,null),
('ORB_OF_THE_FIRMAMENT',8,2,6000,null),
('ORB_OF_DRIVING_RAIN',8,2,6000,null),
('ORB_OF_TEMPESTUOUS_FIRE',8,2,6000,null),
('TOME_OF_EARTH',8,3,20000,null),
('TOME_OF_AIR',8,3,20000,null),
('TOME_OF_WATER',8,3,20000,null),
('TOME_OF_FIRE',8,3,20000,null),
('SPHERE_OF_PERMANENCE',8,2,7500,null),
('ORB_OF_INHIBITION',8,3,20000,null),
('ORB_OF_VULNERABILITY',8,3,25000,null),
('BIRD_OF_PERCEPTION',8,0,1000,null),
('STOIC_WATCHMAN',8,0,2000,null),
('EMBLEM_OF_COGNIZANCE',8,1,3000,null),
('CLOVER_OF_FORTUNE',8,0,1000,null),
('LADYBIRD_OF_LUCK',8,0,1000,null),
('CARDS_OF_PROPHECY',8,0,1000,null),
('HOURGLASS_OF_THE_EVIL_HOUR',8,0,2000,null),
('GLYPH_OF_GALLANTRY',8,0,1000,null),
('CREST_OF_VALOR',8,0,1000,null),
('BADGE_OF_COURAGE',8,0,1000,null),
('SPIRIT_OF_OPPRESSION',8,0,2000,null),
('SPYGLASS',8,0,1000,null),
('SPECULUM',8,0,1000,null),
('GOLDEN_BOW',8,2,8000,null),
('BOW_OF_ELVEN_CHERRYWOOD',8,0,2000,(SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER')),
('BOWSTRING_OF_THE_UNICORNS_MANE',8,1,4000,(SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER')),
('ANGEL_FEATHER_ARROWS',8,2,6000,(SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER')),
('VIAL_OF_LIFEBLOOD',8,2,10000,(SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE')),
('ENDLESS_PURSE_OF_GOLD',8,2,5000,null),
('ENDLESS_BAG_OF_GOLD',8,2,7500,null),
('ENDLESS_SACK_OF_GOLD',8,3,10000,null),
('INEXHAUSTIBLE_CART_OF_LUMBER',8,1,5000,null),
('INEXHAUSTIBLE_CART_OF_ORE',8,1,5000,null),
('EVERPOURING_VIAL_OF_MERCURY',8,2,5000,(SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA')),
('LEGS_OF_LEGION',8,0,5000,(SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION')),
('LOINS_OF_LEGION',8,1,5000,(SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION')),
('TORSO_OF_LEGION',8,1,5000,(SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION')),
('ARMS_OF_LEGION',8,2,5000,(SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION')),
('HEAD_OF_LEGION',8,2,5000,(SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION')),
('SHACKLES_OF_WAR',8,2,5000,null),
('VIAL_OF_DRAGON_BLOOD',8,3,20000,null),
('PENDANT_OF_DISPASSION',2,0,1000,null),
('PENDANT_OF_FREE_WILL',2,0,1000,null),
('PENDANT_OF_LIFE',2,0,2500,null),
('PENDANT_OF_DEATH',2,0,2500,null),
('PENDANT_OF_TOTAL_RECALL',2,0,3000,null),
('PENDANT_OF_HOLINESS',2,0,5000,null),
('PENDANT_OF_SECOND_SIGHT',2,2,5000,null),
('PENDANT_OF_NEGATIVITY',2,2,5000,null),
('COLLAR_OF_CONJURING',2,0,500,(SELECT id FROM artifact WHERE full_name = 'RING_OF_THE_MAGI')),
('AMULET_OF_THE_UNDERTAKER',2,0,2000,(SELECT id FROM artifact WHERE full_name = 'CLOAK_OF_THE_UNDEAD_KING')),
('GARNITURE_OF_INTERFERENCE',2,2,2000,null),
('STATESMANS_MEDAL',2,2,5000,null),
('NECKLACE_OF_SWIFTNESS',2,0,5000,null),
('PENDANT_OF_COURAGE',2,2,7000,null),
('NECKLACE_OF_DRAGONTEETH',2,2,6000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('NECKLACE_OF_OCEAN_GUIDANCE',2,2,10000,(SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT')),
('CELESTIAL_NECKLACE_OF_BLISS',2,3,12000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('CENTAURS_AXE',3,0,2000,null),
('BLACKSHARD_OF_THE_DEAD_KNIGHT',3,1,3000,(SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED')),
('GREATER_GNOLLS_FLAIL',3,1,4000,null),
('OGRES_CLUB_OF_HAVOC',3,2,5000,null),
('SWORD_OF_HELLFIRE',3,2,6000,(SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE_(CAMPAIGN_ONLY)')),
('RED_DRAGON_FLAME_TONGUE',3,1,4000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('TITANS_GLADIUS',3,3,10000,(SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER')),
('SWORD_OF_JUDGEMENT',3,3,20000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('ARMAGEDDONS_BLADE',3,3,50000,null),
('RING_OF_CONJURING',6,0,1000,(SELECT id FROM artifact WHERE full_name = 'RING_OF_THE_MAGI')),
('STILL_EYE_OF_THE_DRAGON',6,0,2000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('QUIET_EYE_OF_THE_DRAGON',6,0,2000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('EQUESTRIANS_GLOVES',6,1,3000,null),
('DIPLOMATS_RING',6,2,5000,null),
('RING_OF_THE_WAYFARER',6,2,5000,null),
('RING_OF_VITALITY',6,0,5000,(SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE')),
('RING_OF_LIFE',6,1,5000,(SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE')),
('RING_OF_INFINITE_GEMS',6,2,5000,(SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA')),
('EVERSMOKING_RING_OF_SULFUR',6,2,5000,(SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA')),
('BREASTPLATE_OF_PETRIFIED_WOOD',5,0,1000,null),
('RIB_CAGE',5,1,3000,(SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED')),
('SCALES_OF_THE_GREATER_BASILISK',5,1,4000,null),
('TUNIC_OF_THE_CYCLOPS_KING',5,2,5000,null),
('BREASTPLATE_OF_BRIMSTONE',5,2,6000,(SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE_(CAMPAIGN_ONLY)')),
('ARMOR_OF_WONDER',5,1,4000,(SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE')),
('DRAGON_SCALE_ARMOR',5,3,8000,(SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER')),
('TITANS_CUIRASS',5,3,10000,(SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'));

create table bonus_type (
	id int4 not null primary key,
	full_name varchar not null
);

--drop table bonus_type;

insert into bonus_type (
id, full_name
) values
(0, 'ATTACK'),
(1, 'DEFENSE'),
(2, 'SPELL_POWER'),
(3, 'KNOWLEDGE'),
(4, 'SPELL_DURATION'),
(5, 'NECROMANCY'),
(6, 'MAGIC_RESISTANCE'),
(7, 'SURRENDERING_COST'),
(8, 'CRYSTAL_DAILY'),
(9, 'PREVENTS_CAST'),
(10, 'SPEED'),
(11, 'FLY'),
(12, 'MOVEMENT_POINTS'),
(13, 'WATER_WALK'),
(14, 'SEA_MOVEMENT_POINTS'),
(15, 'GRANTS_SPELL'),
(16, 'WHIRLPOOL_PROTECTION'),
(17, 'GRANTS_SPELL_LEVEL'),
(18, 'GRANTS_SPELL_SCHOOL'),
(19, 'NO_PENALTY_SHIP_BOARDING'),
(20, 'MANA_POINTS'),
(21, 'EARTH_SPELL_DAMAGE'),
(22, 'AIR_SPELL_DAMAGE'),
(23, 'WATER_SPELL_DAMAGE'),
(24, 'FIRE_SPELL_DAMAGE'),
(25, 'SPELL_IMMUNE'),
(26, 'PREVENTS_SPELLCAST'),
(27, 'REMOVE_IMMUNITIES'),
(28, 'EAGLE_EYE'),
(29, 'LUCK'),
(30, 'MORALE'),
(31, 'LUCK_DISABLE'),
(32, 'MORALE_DISABLE'),
(33, 'MIND_IMMUNE'),
(34, 'SCOUTING'),
(35, 'NO_RANGE_PENALTY'),
(36, 'NO_OBSTACLE_PENALTY'),
(37, 'NO_MELEE_PENALTY'),
(38, 'BLOCKED_SHOOTING'),
(39, 'ARCHERY'),
(40, 'HEALTH'),
(41, 'HEALTH_PERCENTAGE'),
(42, 'MANA_POINTS_PERCENTAGE'),
(43, 'REGENERATION'),
(44, 'GOLD_DAILY'),
(45, 'GEMS_DAILY'),
(46, 'SULFUR_DAILY'),
(47, 'MERCURY_DAILY'),
(48, 'LUMBER_DAILY'),
(49, 'LEVEL_2_GROWTH'),
(50, 'LEVEL_3_GROWTH'),
(51, 'LEVEL_4_GROWTH'),
(52, 'LEVEL_5_GROWTH'),
(53, 'LEVEL_6_GROWTH'),
(54, 'PERCENTAGE_GROWTH'),
(55, 'PREVENTS_RETREAT'),
(56, 'PREVENTS_SURRENDER'),
(57, 'DRAGON_ATTACK'),
(58, 'DRAGON_DEFENSE'),
(59, 'ADDS_SPELL_BOOK'),
(60, 'CASTS_PRAYER'),
(61, 'SPELL_LEVEL_IMMUNE'),
(62, 'CASTS_AOTD'),
(63, 'ORE_DAILY'),
(64, 'NO_ALIGNMENT_PENALTY');

create table artifact_bonus (
	id serial primary key,
	artifact_id int4 not null,
	bonus_type int4 not null,
	bonus_value int4
);

--drop table artifact_bonus;

insert into artifact_bonus (
artifact_id, bonus_type, bonus_value
) values
((SELECT id FROM artifact WHERE full_name = 'CAPE_OF_CONJURING'),(select id from bonus_type where full_name = 'SPELL_DURATION'),3),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_WING_TABARD'),(select id from bonus_type where full_name = 'SPELL_POWER'),2),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_WING_TABARD'),(select id from bonus_type where full_name = 'KNOWLEDGE'),2),
((SELECT id FROM artifact WHERE full_name = 'VAMPIRES_COWL'),(select id from bonus_type where full_name = 'NECROMANCY'),10),
((SELECT id FROM artifact WHERE full_name = 'SURCOAT_OF_COUNTERPOISE'),(select id from bonus_type where full_name = 'MAGIC_RESISTANCE'),10),
((SELECT id FROM artifact WHERE full_name = 'AMBASSADORS_SASH'),(select id from bonus_type where full_name = 'SURRENDERING_COST'),10),
((SELECT id FROM artifact WHERE full_name = 'EVERFLOWING_CRYSTAL_CLOAK'),(select id from bonus_type where full_name = 'CRYSTAL_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'RECANTERS_CLOAK'),(select id from bonus_type where full_name = 'PREVENTS_CAST'),1),
((SELECT id FROM artifact WHERE full_name = 'RECANTERS_CLOAK'),(select id from bonus_type where full_name = 'PREVENTS_CAST'),2),
((SELECT id FROM artifact WHERE full_name = 'RECANTERS_CLOAK'),(select id from bonus_type where full_name = 'PREVENTS_CAST'),3),
((SELECT id FROM artifact WHERE full_name = 'CAPE_OF_VELOCITY'),(select id from bonus_type where full_name = 'SPEED'),2),
((SELECT id FROM artifact WHERE full_name = 'ANGEL_WINGS'),(select id from bonus_type where full_name = 'FLY'),3),
((SELECT id FROM artifact WHERE full_name = 'CLOAK_OF_THE_UNDEAD_KING'),(select id from bonus_type where full_name = 'NECROMANCY'),60),
((SELECT id FROM artifact WHERE full_name = 'DRAGONBONE_GREAVES'),(select id from bonus_type where full_name = 'KNOWLEDGE'),1),
((SELECT id FROM artifact WHERE full_name = 'DRAGONBONE_GREAVES'),(select id from bonus_type where full_name = 'SPELL_POWER'),1),
((SELECT id FROM artifact WHERE full_name = 'BOOTS_OF_SPEED'),(select id from bonus_type where full_name = 'MOVEMENT_POINTS'),600),
((SELECT id FROM artifact WHERE full_name = 'DEAD_MANS_BOOTS'),(select id from bonus_type where full_name = 'NECROMANCY'),15),
((SELECT id FROM artifact WHERE full_name = 'BOOTS_OF_POLARITY'),(select id from bonus_type where full_name = 'MAGIC_RESISTANCE'),15),
((SELECT id FROM artifact WHERE full_name = 'SANDALS_OF_THE_SAINT'),(select id from bonus_type where full_name = 'ATTACK'),2),
((SELECT id FROM artifact WHERE full_name = 'SANDALS_OF_THE_SAINT'),(select id from bonus_type where full_name = 'DEFENSE'),2),
((SELECT id FROM artifact WHERE full_name = 'SANDALS_OF_THE_SAINT'),(select id from bonus_type where full_name = 'SPELL_POWER'),2),
((SELECT id FROM artifact WHERE full_name = 'SANDALS_OF_THE_SAINT'),(select id from bonus_type where full_name = 'KNOWLEDGE'),2),
((SELECT id FROM artifact WHERE full_name = 'BOOTS_OF_LEVITATION'),(select id from bonus_type where full_name = 'WATER_WALK'), 3),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_THE_ALABASTER_UNICORN'),(select id from bonus_type where full_name = 'KNOWLEDGE'),1),
((SELECT id FROM artifact WHERE full_name = 'SKULL_HELMET'),(select id from bonus_type where full_name = 'KNOWLEDGE'),2),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_CHAOS'),(select id from bonus_type where full_name = 'KNOWLEDGE'),3),
((SELECT id FROM artifact WHERE full_name = 'CROWN_OF_THE_SUPREME_MAGI'),(select id from bonus_type where full_name = 'KNOWLEDGE'),4),
((SELECT id FROM artifact WHERE full_name = 'HELLSTORM_HELMET'),(select id from bonus_type where full_name = 'KNOWLEDGE'),5),
((SELECT id FROM artifact WHERE full_name = 'CROWN_OF_DRAGONTOOTH'),(select id from bonus_type where full_name = 'KNOWLEDGE'),4),
((SELECT id FROM artifact WHERE full_name = 'CROWN_OF_DRAGONTOOTH'),(select id from bonus_type where full_name = 'SPELL_POWER'),4),
((SELECT id FROM artifact WHERE full_name = 'THUNDER_HELMET'),(select id from bonus_type where full_name = 'KNOWLEDGE'),10),
((SELECT id FROM artifact WHERE full_name = 'THUNDER_HELMET'),(select id from bonus_type where full_name = 'SPELL_POWER'),-2),
((SELECT id FROM artifact WHERE full_name = 'SEA_CAPTAINS_HAT'),(select id from bonus_type where full_name = 'SEA_MOVEMENT_POINTS'),500),
((SELECT id FROM artifact WHERE full_name = 'SEA_CAPTAINS_HAT'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'SUMMON_BOAT')),
((SELECT id FROM artifact WHERE full_name = 'SEA_CAPTAINS_HAT'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'SCUTTLE_BOAT')),
((SELECT id FROM artifact WHERE full_name = 'SEA_CAPTAINS_HAT'),(select id from bonus_type where full_name = 'WHIRLPOOL_PROTECTION'),null),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_HEAVENLY_ENLIGHTENMENT'),(select id from bonus_type where full_name = 'ATTACK'),6),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_HEAVENLY_ENLIGHTENMENT'),(select id from bonus_type where full_name = 'DEFENSE'),6),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_HEAVENLY_ENLIGHTENMENT'),(select id from bonus_type where full_name = 'SPELL_POWER'),6),
((SELECT id FROM artifact WHERE full_name = 'HELM_OF_HEAVENLY_ENLIGHTENMENT'),(select id from bonus_type where full_name = 'KNOWLEDGE'),6),
((SELECT id FROM artifact WHERE full_name = 'SPELLBINDERS_HAT'),(select id from bonus_type where full_name = 'GRANTS_SPELL_LEVEL'),5),
((SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT'),(select id from bonus_type where full_name = 'SEA_MOVEMENT_POINTS'),1500),
((SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'SUMMON_BOAT')),
((SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'SCUTTLE_BOAT')),
((SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT'),(select id from bonus_type where full_name = 'WHIRLPOOL_PROTECTION'),null),
((SELECT id FROM artifact WHERE full_name = 'ADMIRALS_HAT'),(select id from bonus_type where full_name = 'NO_PENALTY_SHIP_BOARDING'),null),
((SELECT id FROM artifact WHERE full_name = 'SHIELD_OF_THE_DWARVEN_LORDS'),(select id from bonus_type where full_name = 'DEFENSE'),2),
((SELECT id FROM artifact WHERE full_name = 'SHIELD_OF_THE_YAWNING_DEAD'),(select id from bonus_type where full_name = 'DEFENSE'),3),
((SELECT id FROM artifact WHERE full_name = 'BUCKLER_OF_THE_GNOLL_KING'),(select id from bonus_type where full_name = 'DEFENSE'),4),
((SELECT id FROM artifact WHERE full_name = 'TARG_OF_THE_RAMPAGING_OGRE'),(select id from bonus_type where full_name = 'DEFENSE'),5),
((SELECT id FROM artifact WHERE full_name = 'SHIELD_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'DEFENSE'),6),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_SCALE_SHIELD'),(select id from bonus_type where full_name = 'DEFENSE'),3),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_SCALE_SHIELD'),(select id from bonus_type where full_name = 'ATTACK'),3),
((SELECT id FROM artifact WHERE full_name = 'LIONS_SHIELD_OF_COURAGE'),(select id from bonus_type where full_name = 'ATTACK'),4),
((SELECT id FROM artifact WHERE full_name = 'LIONS_SHIELD_OF_COURAGE'),(select id from bonus_type where full_name = 'DEFENSE'),4),
((SELECT id FROM artifact WHERE full_name = 'LIONS_SHIELD_OF_COURAGE'),(select id from bonus_type where full_name = 'SPELL_POWER'),4),
((SELECT id FROM artifact WHERE full_name = 'LIONS_SHIELD_OF_COURAGE'),(select id from bonus_type where full_name = 'KNOWLEDGE'),4),
((SELECT id FROM artifact WHERE full_name = 'SENTINELS_SHIELD'),(select id from bonus_type where full_name = 'DEFENSE'),12),
((SELECT id FROM artifact WHERE full_name = 'SENTINELS_SHIELD'),(select id from bonus_type where full_name = 'ATTACK'),-3),
((SELECT id FROM artifact WHERE full_name = 'CHARM_OF_MANA'),(select id from bonus_type where full_name = 'MANA_POINTS'),1),
((SELECT id FROM artifact WHERE full_name = 'TALISMAN_OF_MANA'),(select id from bonus_type where full_name = 'MANA_POINTS'),2),
((SELECT id FROM artifact WHERE full_name = 'MYSTIC_ORB_OF_MANA'),(select id from bonus_type where full_name = 'MANA_POINTS'),3),
((SELECT id FROM artifact WHERE full_name = 'WIZARDS_WELL'),(select id from bonus_type where full_name = 'MANA_POINTS_PERCENTAGE'),100),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_SILT'),(select id from bonus_type where full_name = 'EARTH_SPELL_DAMAGE'),50),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_THE_FIRMAMENT'),(select id from bonus_type where full_name = 'AIR_SPELL_DAMAGE'),50),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_DRIVING_RAIN'),(select id from bonus_type where full_name = 'WATER_SPELL_DAMAGE'),50),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_TEMPESTUOUS_FIRE'),(select id from bonus_type where full_name = 'FIRE_SPELL_DAMAGE'),50),
((SELECT id FROM artifact WHERE full_name = 'TOME_OF_EARTH'),(select id from bonus_type where full_name = 'GRANTS_SPELL_SCHOOL'),2),
((SELECT id FROM artifact WHERE full_name = 'TOME_OF_AIR'),(select id from bonus_type where full_name = 'GRANTS_SPELL_SCHOOL'),1),
((SELECT id FROM artifact WHERE full_name = 'TOME_OF_WATER'),(select id from bonus_type where full_name = 'GRANTS_SPELL_SCHOOL'),4),
((SELECT id FROM artifact WHERE full_name = 'TOME_OF_FIRE'),(select id from bonus_type where full_name = 'GRANTS_SPELL_SCHOOL'),3),
((SELECT id FROM artifact WHERE full_name = 'SPHERE_OF_PERMANENCE'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'DISPEL')),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_INHIBITION'),(select id from bonus_type where full_name = 'PREVENTS_SPELLCAST'),null),
((SELECT id FROM artifact WHERE full_name = 'ORB_OF_VULNERABILITY'),(select id from bonus_type where full_name = 'REMOVE_IMMUNITIES'),null),
((SELECT id FROM artifact WHERE full_name = 'BIRD_OF_PERCEPTION'),(select id from bonus_type where full_name = 'EAGLE_EYE'),5),
((SELECT id FROM artifact WHERE full_name = 'STOIC_WATCHMAN'),(select id from bonus_type where full_name = 'EAGLE_EYE'),10),
((SELECT id FROM artifact WHERE full_name = 'EMBLEM_OF_COGNIZANCE'),(select id from bonus_type where full_name = 'EAGLE_EYE'),15),
((SELECT id FROM artifact WHERE full_name = 'CLOVER_OF_FORTUNE'),(select id from bonus_type where full_name = 'LUCK'),1),
((SELECT id FROM artifact WHERE full_name = 'LADYBIRD_OF_LUCK'),(select id from bonus_type where full_name = 'LUCK'),1),
((SELECT id FROM artifact WHERE full_name = 'CARDS_OF_PROPHECY'),(select id from bonus_type where full_name = 'LUCK'),1),
((SELECT id FROM artifact WHERE full_name = 'HOURGLASS_OF_THE_EVIL_HOUR'),(select id from bonus_type where full_name = 'LUCK_DISABLE'),null),
((SELECT id FROM artifact WHERE full_name = 'GLYPH_OF_GALLANTRY'),(select id from bonus_type where full_name = 'MORALE'),1),
((SELECT id FROM artifact WHERE full_name = 'CREST_OF_VALOR'),(select id from bonus_type where full_name = 'MORALE'),1),
((SELECT id FROM artifact WHERE full_name = 'BADGE_OF_COURAGE'),(select id from bonus_type where full_name = 'MORALE'),1),
((SELECT id FROM artifact WHERE full_name = 'BADGE_OF_COURAGE'),(select id from bonus_type where full_name = 'MIND_IMMUNE'),null),
((SELECT id FROM artifact WHERE full_name = 'SPIRIT_OF_OPPRESSION'),(select id from bonus_type where full_name = 'MORALE_DISABLE'),null),
((SELECT id FROM artifact WHERE full_name = 'SPYGLASS'),(select id from bonus_type where full_name = 'SCOUTING'),1),
((SELECT id FROM artifact WHERE full_name = 'SPECULUM'),(select id from bonus_type where full_name = 'SCOUTING'),1),
((SELECT id FROM artifact WHERE full_name = 'GOLDEN_BOW'),(select id from bonus_type where full_name = 'NO_RANGE_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'GOLDEN_BOW'),(select id from bonus_type where full_name = 'NO_OBSTACLE_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_ELVEN_CHERRYWOOD'),(select id from bonus_type where full_name = 'ARCHERY'),5),
((SELECT id FROM artifact WHERE full_name = 'BOWSTRING_OF_THE_UNICORNS_MANE'),(select id from bonus_type where full_name = 'ARCHERY'),10),
((SELECT id FROM artifact WHERE full_name = 'ANGEL_FEATHER_ARROWS'),(select id from bonus_type where full_name = 'ARCHERY'),15),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER'),(select id from bonus_type where full_name = 'ARCHERY'),30),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER'),(select id from bonus_type where full_name = 'NO_RANGE_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER'),(select id from bonus_type where full_name = 'NO_MELEE_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER'),(select id from bonus_type where full_name = 'NO_OBSTACLE_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'BOW_OF_THE_SHARPSHOOTER'),(select id from bonus_type where full_name = 'BLOCKED_SHOOTING'),null),
((SELECT id FROM artifact WHERE full_name = 'VIAL_OF_LIFEBLOOD'),(select id from bonus_type where full_name = 'HEALTH'),2),
((SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE'),(select id from bonus_type where full_name = 'HEALTH'), 4),
((SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE'),(select id from bonus_type where full_name = 'HEALTH_PERCENTAGE'),25),
((SELECT id FROM artifact WHERE full_name = 'ELIXIR_OF_LIFE'),(select id from bonus_type where full_name = 'REGENERATION'),50),
((SELECT id FROM artifact WHERE full_name = 'ENDLESS_PURSE_OF_GOLD'),(select id from bonus_type where full_name = 'GOLD_DAILY'),500),
((SELECT id FROM artifact WHERE full_name = 'ENDLESS_BAG_OF_GOLD'),(select id from bonus_type where full_name = 'GOLD_DAILY'),750),
((SELECT id FROM artifact WHERE full_name = 'ENDLESS_SACK_OF_GOLD'),(select id from bonus_type where full_name = 'GOLD_DAILY'),1000),
((SELECT id FROM artifact WHERE full_name = 'INEXHAUSTIBLE_CART_OF_LUMBER'),(select id from bonus_type where full_name = 'LUMBER_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'INEXHAUSTIBLE_CART_OF_ORE'),(select id from bonus_type where full_name = 'ORE_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'EVERPOURING_VIAL_OF_MERCURY'),(select id from bonus_type where full_name = 'MERCURY_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA'),(select id from bonus_type where full_name = 'MERCURY_DAILY'),5),
((SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA'),(select id from bonus_type where full_name = 'CRYSTAL_DAILY'),5),
((SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA'),(select id from bonus_type where full_name = 'SULFUR_DAILY'),5),
((SELECT id FROM artifact WHERE full_name = 'CORNUCOPIA'),(select id from bonus_type where full_name = 'GEMS_DAILY'),5),
((SELECT id FROM artifact WHERE full_name = 'LEGS_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_2_GROWTH'),5),
((SELECT id FROM artifact WHERE full_name = 'LOINS_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_3_GROWTH'),4),
((SELECT id FROM artifact WHERE full_name = 'TORSO_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_4_GROWTH'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMS_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_5_GROWTH'),2),
((SELECT id FROM artifact WHERE full_name = 'HEAD_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_6_GROWTH'),1),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'PERCENTAGE_GROWTH'),50),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_2_GROWTH'),5),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_3_GROWTH'),4),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_4_GROWTH'),3),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_5_GROWTH'),2),
((SELECT id FROM artifact WHERE full_name = 'STATUE_OF_LEGION'),(select id from bonus_type where full_name = 'LEVEL_6_GROWTH'),1),
((SELECT id FROM artifact WHERE full_name = 'SHACKLES_OF_WAR'),(select id from bonus_type where full_name = 'PREVENTS_RETREAT'),null),
((SELECT id FROM artifact WHERE full_name = 'SHACKLES_OF_WAR'),(select id from bonus_type where full_name = 'PREVENTS_SURRENDER'),null),
((SELECT id FROM artifact WHERE full_name = 'VIAL_OF_DRAGON_BLOOD'),(select id from bonus_type where full_name = 'DRAGON_ATTACK'),5),
((SELECT id FROM artifact WHERE full_name = 'VIAL_OF_DRAGON_BLOOD'),(select id from bonus_type where full_name = 'DRAGON_DEFENSE'),5),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_DISPASSION'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'BERSERK')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_FREE_WILL'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'HYPNOTIZE')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_LIFE'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'DEATH_RIPPLE')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_DEATH'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'DESTROY_UNDEAD')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_TOTAL_RECALL'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'FORGETFULNESS')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_HOLINESS'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'CURSE')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_SECOND_SIGHT'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'BLIND')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_NEGATIVITY'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'LIGHTNING_BOLT')),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_NEGATIVITY'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'CHAIN_LIGHTNING')),
((SELECT id FROM artifact WHERE full_name = 'COLLAR_OF_CONJURING'),(select id from bonus_type where full_name = 'SPELL_DURATION'),1),
((SELECT id FROM artifact WHERE full_name = 'AMULET_OF_THE_UNDERTAKER'),(select id from bonus_type where full_name = 'NECROMANCY'),5),
((SELECT id FROM artifact WHERE full_name = 'GARNITURE_OF_INTERFERENCE'),(select id from bonus_type where full_name = 'MAGIC_RESISTANCE'),5),
((SELECT id FROM artifact WHERE full_name = 'STATESMANS_MEDAL'),(select id from bonus_type where full_name = 'SURRENDERING_COST'),10),
((SELECT id FROM artifact WHERE full_name = 'NECKLACE_OF_SWIFTNESS'),(select id from bonus_type where full_name = 'SPEED'),1),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_COURAGE'),(select id from bonus_type where full_name = 'LUCK'),3),
((SELECT id FROM artifact WHERE full_name = 'PENDANT_OF_COURAGE'),(select id from bonus_type where full_name = 'MORALE'),3),
((SELECT id FROM artifact WHERE full_name = 'NECKLACE_OF_DRAGONTEETH'),(select id from bonus_type where full_name = 'SPELL_POWER'),3),
((SELECT id FROM artifact WHERE full_name = 'NECKLACE_OF_DRAGONTEETH'),(select id from bonus_type where full_name = 'KNOWLEDGE'),3),
((SELECT id FROM artifact WHERE full_name = 'NECKLACE_OF_OCEAN_GUIDANCE'),(select id from bonus_type where full_name = 'SEA_MOVEMENT_POINTS'),1000),
((SELECT id FROM artifact WHERE full_name = 'CELESTIAL_NECKLACE_OF_BLISS'),(select id from bonus_type where full_name = 'ATTACK'),3),
((SELECT id FROM artifact WHERE full_name = 'CELESTIAL_NECKLACE_OF_BLISS'),(select id from bonus_type where full_name = 'DEFENSE'),3),
((SELECT id FROM artifact WHERE full_name = 'CELESTIAL_NECKLACE_OF_BLISS'),(select id from bonus_type where full_name = 'SPELL_POWER'),3),
((SELECT id FROM artifact WHERE full_name = 'CELESTIAL_NECKLACE_OF_BLISS'),(select id from bonus_type where full_name = 'KNOWLEDGE'),3),
((SELECT id FROM artifact WHERE full_name = 'CENTAURS_AXE'),(select id from bonus_type where full_name = 'ATTACK'),2),
((SELECT id FROM artifact WHERE full_name = 'BLACKSHARD_OF_THE_DEAD_KNIGHT'),(select id from bonus_type where full_name = 'ATTACK'),3),
((SELECT id FROM artifact WHERE full_name = 'GREATER_GNOLLS_FLAIL'),(select id from bonus_type where full_name = 'ATTACK'),4),
((SELECT id FROM artifact WHERE full_name = 'OGRES_CLUB_OF_HAVOC'),(select id from bonus_type where full_name = 'ATTACK'),5),
((SELECT id FROM artifact WHERE full_name = 'SWORD_OF_HELLFIRE'),(select id from bonus_type where full_name = 'ATTACK'),6),
((SELECT id FROM artifact WHERE full_name = 'RED_DRAGON_FLAME_TONGUE'),(select id from bonus_type where full_name = 'DEFENSE'),2),
((SELECT id FROM artifact WHERE full_name = 'RED_DRAGON_FLAME_TONGUE'),(select id from bonus_type where full_name = 'ATTACK'),2),
((SELECT id FROM artifact WHERE full_name = 'TITANS_GLADIUS'),(select id from bonus_type where full_name = 'DEFENSE'),-3),
((SELECT id FROM artifact WHERE full_name = 'TITANS_GLADIUS'),(select id from bonus_type where full_name = 'ATTACK'),12),
((SELECT id FROM artifact WHERE full_name = 'SWORD_OF_JUDGEMENT'),(select id from bonus_type where full_name = 'ATTACK'),5),
((SELECT id FROM artifact WHERE full_name = 'SWORD_OF_JUDGEMENT'),(select id from bonus_type where full_name = 'DEFENSE'),5),
((SELECT id FROM artifact WHERE full_name = 'SWORD_OF_JUDGEMENT'),(select id from bonus_type where full_name = 'SPELL_POWER'),5),
((SELECT id FROM artifact WHERE full_name = 'SWORD_OF_JUDGEMENT'),(select id from bonus_type where full_name = 'KNOWLEDGE'),5),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'ATTACK'),9),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'DEFENSE'),9),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'SPELL_POWER'),8),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'KNOWLEDGE'),8),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'TITANS_LIGHTNING_BOLT')),
((SELECT id FROM artifact WHERE full_name = 'TITANS_THUNDER'),(select id from bonus_type where full_name = 'ADDS_SPELL_BOOK'),null),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'ATTACK'),21),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'DEFENSE'),21),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'SPELL_POWER'),21),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'KNOWLEDGE'),21),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'NO_ALIGNMENT_PENALTY'),null),
((SELECT id FROM artifact WHERE full_name = 'ANGELIC_ALLIANCE'),(select id from bonus_type where full_name = 'CASTS_PRAYER'),10),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'ATTACK'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'DEFENSE'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'SPELL_POWER'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'KNOWLEDGE'),6),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'GRANTS_SPELL'),(select id from spell where full_name = 'ARMAGEDDON')),
((SELECT id FROM artifact WHERE full_name = 'ARMAGEDDONS_BLADE'),(select id from bonus_type where full_name = 'SPELL_IMMUNE'),(select id from spell where full_name = 'ARMAGEDDON')),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_CONJURING'),(select id from bonus_type where full_name = 'SPELL_DURATION'),2),
((SELECT id FROM artifact WHERE full_name = 'STILL_EYE_OF_THE_DRAGON'),(select id from bonus_type where full_name = 'MORALE'),1),
((SELECT id FROM artifact WHERE full_name = 'STILL_EYE_OF_THE_DRAGON'),(select id from bonus_type where full_name = 'LUCK'),1),
((SELECT id FROM artifact WHERE full_name = 'QUIET_EYE_OF_THE_DRAGON'),(select id from bonus_type where full_name = 'ATTACK'),1),
((SELECT id FROM artifact WHERE full_name = 'QUIET_EYE_OF_THE_DRAGON'),(select id from bonus_type where full_name = 'DEFENSE'),1),
((SELECT id FROM artifact WHERE full_name = 'EQUESTRIANS_GLOVES'),(select id from bonus_type where full_name = 'MOVEMENT_POINTS'),300),
((SELECT id FROM artifact WHERE full_name = 'DIPLOMATS_RING'),(select id from bonus_type where full_name = 'SURRENDERING_COST'),10),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_THE_WAYFARER'),(select id from bonus_type where full_name = 'SPEED'),1),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_VITALITY'),(select id from bonus_type where full_name = 'HEALTH'),1),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_LIFE'),(select id from bonus_type where full_name = 'HEALTH'),1),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_INFINITE_GEMS'),(select id from bonus_type where full_name = 'GEMS_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'EVERSMOKING_RING_OF_SULFUR'),(select id from bonus_type where full_name = 'SULFUR_DAILY'),1),
((SELECT id FROM artifact WHERE full_name = 'RING_OF_THE_MAGI'),(select id from bonus_type where full_name = 'SPELL_DURATION'),56),
((SELECT id FROM artifact WHERE full_name = 'BREASTPLATE_OF_PETRIFIED_WOOD'),(select id from bonus_type where full_name = 'SPELL_POWER'),1),
((SELECT id FROM artifact WHERE full_name = 'RIB_CAGE'),(select id from bonus_type where full_name = 'SPELL_POWER'),2),
((SELECT id FROM artifact WHERE full_name = 'SCALES_OF_THE_GREATER_BASILISK'),(select id from bonus_type where full_name = 'SPELL_POWER'),3),
((SELECT id FROM artifact WHERE full_name = 'TUNIC_OF_THE_CYCLOPS_KING'),(select id from bonus_type where full_name = 'SPELL_POWER'),4),
((SELECT id FROM artifact WHERE full_name = 'BREASTPLATE_OF_BRIMSTONE'),(select id from bonus_type where full_name = 'SPELL_POWER'),5),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_WONDER'),(select id from bonus_type where full_name = 'ATTACK'),1),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_WONDER'),(select id from bonus_type where full_name = 'DEFENSE'),1),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_WONDER'),(select id from bonus_type where full_name = 'SPELL_POWER'),1),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_WONDER'),(select id from bonus_type where full_name = 'KNOWLEDGE'),1),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_SCALE_ARMOR'),(select id from bonus_type where full_name = 'ATTACK'),4),
((SELECT id FROM artifact WHERE full_name = 'DRAGON_SCALE_ARMOR'),(select id from bonus_type where full_name = 'DEFENSE'),4),
((SELECT id FROM artifact WHERE full_name = 'TITANS_CUIRASS'),(select id from bonus_type where full_name = 'SPELL_POWER'),10),
((SELECT id FROM artifact WHERE full_name = 'TITANS_CUIRASS'),(select id from bonus_type where full_name = 'KNOWLEDGE'),-2),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'ATTACK'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'DEFENSE'),3),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'SPELL_POWER'),2),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'KNOWLEDGE'),2),
((SELECT id FROM artifact WHERE full_name = 'ARMOR_OF_THE_DAMNED'),(select id from bonus_type where full_name = 'CASTS_AOTD'),50),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'ATTACK'),16),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'DEFENSE'),16),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'SPELL_POWER'),16),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'KNOWLEDGE'),16),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'MORALE'),1),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'LUCK'),1),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'SPELL_LEVEL_IMMUNE'),1),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'SPELL_LEVEL_IMMUNE'),2),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'SPELL_LEVEL_IMMUNE'),3),
((SELECT id FROM artifact WHERE full_name = 'POWER_OF_THE_DRAGON_FATHER'),(select id from bonus_type where full_name = 'SPELL_LEVEL_IMMUNE'),4);

