create table creature_feature (
id serial primary key,
creature_id int4 not null,
full_name varchar not null,
effect int4,
CONSTRAINT fk_creature FOREIGN KEY(creature_id) REFERENCES creature(id)
);

-- drop table creature_feature;

insert into creature_feature (
	creature_id, full_name, effect
) values
((select id from creature where full_name = 'PIKEMAN'), 'IMMUNE_JOUSTING', null),
((select id from creature where full_name = 'HALBERDIER'), 'IMMUNE_JOUSTING', null),
((select id from creature where full_name = 'ARCHER'), 'RANGED', 12),
((select id from creature where full_name = 'MARKSMAN'), 'RANGED', 24),
((select id from creature where full_name = 'MARKSMAN'), 'DOUBLE_SHOT', null),
((select id from creature where full_name = 'GRIFFIN'), 'FLYING', null),
((select id from creature where full_name = 'GRIFFIN'), 'RETALIATES', 2),
((select id from creature where full_name = 'GRIFFIN'), 'TWO_HEX', null),
((select id from creature where full_name = 'ROYAL_GRIFFIN'), 'FLYING', null),
((select id from creature where full_name = 'ROYAL_GRIFFIN'), 'RETALIATES', 100),
((select id from creature where full_name = 'ROYAL_GRIFFIN'), 'TWO_HEX', null),
((select id from creature where full_name = 'CRUSADER'), 'DOUBLE_ATTACK', null),
((select id from creature where full_name = 'MONK'), 'RANGED', 12),
((select id from creature where full_name = 'ZEALOT'), 'RANGED', 24),
((select id from creature where full_name = 'ZEALOT'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'CAVALIER'), 'JOUSTING', 5),
((select id from creature where full_name = 'CAVALIER'), 'TWO_HEX', null),
((select id from creature where full_name = 'CHAMPION'), 'JOUSTING', 5),
((select id from creature where full_name = 'CHAMPION'), 'TWO_HEX', null),
((select id from creature where full_name = 'ANGEL'), 'FLYING', null),
((select id from creature where full_name = 'ANGEL'), 'PLUS_MORALE', 1),
((select id from creature where full_name = 'ANGEL'), 'HATES', (select id from creature where full_name = 'DEVIL')),
((select id from creature where full_name = 'ANGEL'), 'HATES', (select id from creature where full_name = 'ARCH_DEVIL')),
((select id from creature where full_name = 'ARCHANGEL'), 'FLYING', null),
((select id from creature where full_name = 'ARCHANGEL'), 'PLUS_MORALE', 1),
((select id from creature where full_name = 'ARCHANGEL'), 'HATES', (select id from creature where full_name = 'DEVIL')),
((select id from creature where full_name = 'ARCHANGEL'), 'HATES', (select id from creature where full_name = 'ARCH_DEVIL')),
((select id from creature where full_name = 'ARCHANGEL'), 'TWO_HEX', null),
((select id from creature where full_name = 'ARCHANGEL'), 'SPELLCASTER', 1),
---------------------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'CENTAUR'), 'TWO_HEX', null),
((select id from creature where full_name = 'CENTAUR_CAPTAIN'), 'TWO_HEX', null),
((select id from creature where full_name = 'DWARF'), 'MAGIC_RESISTANCE', 20),
((select id from creature where full_name = 'BATTLE_DWARF'), 'MAGIC_RESISTANCE', 40),
((select id from creature where full_name = 'WOOD_ELF'), 'RANGED', 24),
((select id from creature where full_name = 'GRAND_ELF'), 'RANGED', 24),
((select id from creature where full_name = 'GRAND_ELF'), 'DOUBLE_SHOT', null),
((select id from creature where full_name = 'PEGASUS'), 'TWO_HEX', null),
((select id from creature where full_name = 'PEGASUS'), 'FLYING', null),
((select id from creature where full_name = 'PEGASUS'), 'MAGIC_DAMPER', 2),
((select id from creature where full_name = 'SILVER_PEGASUS'), 'TWO_HEX', null),
((select id from creature where full_name = 'SILVER_PEGASUS'), 'FLYING', null),
((select id from creature where full_name = 'SILVER_PEGASUS'), 'MAGIC_DAMPER', 2),
((select id from creature where full_name = 'DENDROID_GUARD'), 'BINDING', null),
((select id from creature where full_name = 'DENDROID_SOLDIER'), 'BINDING', null),
((select id from creature where full_name = 'UNICORN'), 'TWO_HEX', null),
((select id from creature where full_name = 'UNICORN'), 'BLIND', null),
((select id from creature where full_name = 'UNICORN'), 'AURA_OF_RESISTANCE', 20),
((select id from creature where full_name = 'WAR_UNICORN'), 'TWO_HEX', null),
((select id from creature where full_name = 'WAR_UNICORN'), 'BLIND', null),
((select id from creature where full_name = 'WAR_UNICORN'), 'AURA_OF_RESISTANCE', 20),
((select id from creature where full_name = 'GREEN_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'GREEN_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'GREEN_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'GREEN_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'GREEN_DRAGON'), 'SPELL_IMMUNE', 3),
((select id from creature where full_name = 'GOLD_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'GOLD_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'GOLD_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'GOLD_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'GOLD_DRAGON'), 'SPELL_IMMUNE', 4),
-------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'MASTER_GREMLIN'), 'RANGED', 8),
((select id from creature where full_name = 'STONE_GARGOYLE'), 'UNLIVING', null),
((select id from creature where full_name = 'STONE_GARGOYLE'), 'FLYING', null),
((select id from creature where full_name = 'OBSIDIAN_GARGOYLE'), 'UNLIVING', null),
((select id from creature where full_name = 'OBSIDIAN_GARGOYLE'), 'FLYING', null),
((select id from creature where full_name = 'STONE_GOLEM'), 'UNLIVING', null),
((select id from creature where full_name = 'STONE_GOLEM'), 'SPELL_RESISTANCE', 50),
((select id from creature where full_name = 'IRON_GOLEM'), 'UNLIVING', null),
((select id from creature where full_name = 'IRON_GOLEM'), 'SPELL_RESISTANCE', 75),
((select id from creature where full_name = 'MAGE'), 'RANGED', 24),
((select id from creature where full_name = 'MAGE'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'MAGE'), 'RECUDE_CASTING_COST', 2),
((select id from creature where full_name = 'ARCH_MAGE'), 'RANGED', 24),
((select id from creature where full_name = 'ARCH_MAGE'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'ARCH_MAGE'), 'RECUDE_CASTING_COST', 2),
((select id from creature where full_name = 'ARCH_MAGE'), 'NO_OBSTACLE_PENALTY', null),
((select id from creature where full_name = 'GENIE'), 'FLYING', null),
((select id from creature where full_name = 'GENIE'), 'HATES', (select id from creature where full_name = 'EFREET')),
((select id from creature where full_name = 'GENIE'), 'HATES', (select id from creature where full_name = 'EFREET_SULTAN')),
((select id from creature where full_name = 'MASTER_GENIE'), 'FLYING', null),
((select id from creature where full_name = 'MASTER_GENIE'), 'HATES', (select id from creature where full_name = 'EFREET')),
((select id from creature where full_name = 'MASTER_GENIE'), 'HATES', (select id from creature where full_name = 'EFREET_SULTAN')),
((select id from creature where full_name = 'MASTER_GENIE'), 'SPELLCASTER', 3),
((select id from creature where full_name = 'NAGA'), 'TWO_HEX', null),
((select id from creature where full_name = 'NAGA'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'NAGA_QUEEN'), 'TWO_HEX', null),
((select id from creature where full_name = 'NAGA_QUEEN'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'GIANT'), 'MIND_IMMUNITY', null),
((select id from creature where full_name = 'TITAN'), 'RANGED', 24),
((select id from creature where full_name = 'TITAN'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'TITAN'), 'MIND_IMMUNITY', null),
((select id from creature where full_name = 'TITAN'), 'HATES', (select id from creature where full_name = 'RED_DRAGON')),
((select id from creature where full_name = 'TITAN'), 'HATES', (select id from creature where full_name = 'BLACK_DRAGON')),
-------------------------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'FAMILIAR'), 'MAGIC_CHANNEL', null),
((select id from creature where full_name = 'GOG'), 'RANGED', 12),
((select id from creature where full_name = 'MAGOG'), 'RANGED', 24),
((select id from creature where full_name = 'MAGOG'), 'FIREBALL_ATTACK', null),
((select id from creature where full_name = 'HELL_HOUND'), 'TWO_HEX', null),
((select id from creature where full_name = 'CERBERUS'), 'TWO_HEX', null),
((select id from creature where full_name = 'CERBERUS'), 'THREE_HEADED_ATTACK', null),
((select id from creature where full_name = 'CERBERUS'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'PIT_LORD'), 'SUMMONS_DEMONS', 50),
((select id from creature where full_name = 'EFREET'), 'FLYING', null),
((select id from creature where full_name = 'EFREET'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'EFREET'), 'HATES', (select id from creature where full_name = 'GENIE')),
((select id from creature where full_name = 'EFREET'), 'HATES', (select id from creature where full_name = 'MASTER_GENIE')),
((select id from creature where full_name = 'EFREET_SULTAN'), 'FLYING', null),
((select id from creature where full_name = 'EFREET_SULTAN'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'EFREET_SULTAN'), 'HATES', (select id from creature where full_name = 'GENIE')),
((select id from creature where full_name = 'EFREET_SULTAN'), 'HATES', (select id from creature where full_name = 'MASTER_GENIE')),
((select id from creature where full_name = 'EFREET_SULTAN'), 'FIRE_SHIELD', 20),
((select id from creature where full_name = 'DEVIL'), 'FLYING', null),
((select id from creature where full_name = 'DEVIL'), 'TELEPORTING', null),
((select id from creature where full_name = 'DEVIL'), 'HATES', (select id from creature where full_name = 'ANGEL')),
((select id from creature where full_name = 'DEVIL'), 'HATES', (select id from creature where full_name = 'ARCHANGEL')),
((select id from creature where full_name = 'DEVIL'), 'MINUS_LUCK', 1),
((select id from creature where full_name = 'DEVIL'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'ARCH_DEVIL'), 'FLYING', null),
((select id from creature where full_name = 'ARCH_DEVIL'), 'TELEPORTING', null),
((select id from creature where full_name = 'ARCH_DEVIL'), 'HATES', (select id from creature where full_name = 'ANGEL')),
((select id from creature where full_name = 'ARCH_DEVIL'), 'HATES', (select id from creature where full_name = 'ARCHANGEL')),
((select id from creature where full_name = 'ARCH_DEVIL'), 'MINUS_LUCK', 1),
((select id from creature where full_name = 'ARCH_DEVIL'), 'NO_RETALIATION', null),
-----------------------------------------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'SKELETON'), 'UNDEAD', null),
((select id from creature where full_name = 'SKELETON_WARRIOR'), 'UNDEAD', null),
((select id from creature where full_name = 'WALKING_DEAD'), 'UNDEAD', null),
((select id from creature where full_name = 'ZOMBIE'), 'UNDEAD', null),
((select id from creature where full_name = 'ZOMBIE'), 'DISEASE', 20),
((select id from creature where full_name = 'WIGHT'), 'UNDEAD', null),
((select id from creature where full_name = 'WIGHT'), 'FLYING', null),
((select id from creature where full_name = 'WIGHT'), 'REGENERATION', 50),
((select id from creature where full_name = 'WRAITH'), 'UNDEAD', null),
((select id from creature where full_name = 'WRAITH'), 'FLYING', null),
((select id from creature where full_name = 'WRAITH'), 'REGENERATION', 50),
((select id from creature where full_name = 'WRAITH'), 'MANA_DRAIN', 2),
((select id from creature where full_name = 'VAMPIRE'), 'UNDEAD', null),
((select id from creature where full_name = 'VAMPIRE'), 'FLYING', null),
((select id from creature where full_name = 'VAMPIRE'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'VAMPIRE_LORD'), 'UNDEAD', null),
((select id from creature where full_name = 'VAMPIRE_LORD'), 'FLYING', null),
((select id from creature where full_name = 'VAMPIRE_LORD'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'VAMPIRE_LORD'), 'LIFE_DRAIN', 100),
((select id from creature where full_name = 'LICH'), 'UNDEAD', null),
((select id from creature where full_name = 'LICH'), 'RANGED', 12),
((select id from creature where full_name = 'LICH'), 'DEATH_CLOUD', null),
((select id from creature where full_name = 'POWER_LICH'), 'UNDEAD', null),
((select id from creature where full_name = 'POWER_LICH'), 'RANGED', 24),
((select id from creature where full_name = 'POWER_LICH'), 'DEATH_CLOUD', null),
((select id from creature where full_name = 'BLACK_KNIGHT'), 'UNDEAD', null),
((select id from creature where full_name = 'BLACK_KNIGHT'), 'TWO_HEX', null),
((select id from creature where full_name = 'BLACK_KNIGHT'), 'CURSE', 20),
((select id from creature where full_name = 'DREAD_KNIGHT'), 'UNDEAD', null),
((select id from creature where full_name = 'DREAD_KNIGHT'), 'TWO_HEX', null),
((select id from creature where full_name = 'DREAD_KNIGHT'), 'CURSE', 20),
((select id from creature where full_name = 'DREAD_KNIGHT'), 'DEATH_BLOW', 20),
((select id from creature where full_name = 'BONE_DRAGON'), 'UNDEAD', null),
((select id from creature where full_name = 'BONE_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'BONE_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'BONE_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'BONE_DRAGON'), 'MINUS_MORALE', 1),
((select id from creature where full_name = 'GHOST_DRAGON'), 'UNDEAD', null),
((select id from creature where full_name = 'GHOST_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'GHOST_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'GHOST_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'GHOST_DRAGON'), 'MINUS_MORALE', 1),
((select id from creature where full_name = 'GHOST_DRAGON'), 'AGING', 20),
-----------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'TROGLODYTE'), 'EYELESS', null),
((select id from creature where full_name = 'INFERNAL_TROGLODYTE'), 'EYELESS', null),
((select id from creature where full_name = 'HARPY'), 'FLYING', null),
((select id from creature where full_name = 'HARPY'), 'STRIKE_AND_RETURN', null),
((select id from creature where full_name = 'HARPY_HAG'), 'FLYING', null),
((select id from creature where full_name = 'HARPY_HAG'), 'STRIKE_AND_RETURN', null),
((select id from creature where full_name = 'HARPY_HAG'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'BEHOLDER'), 'RANGED', 12),
((select id from creature where full_name = 'BEHOLDER'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'EVIL_EYE'), 'RANGED', 24),
((select id from creature where full_name = 'EVIL_EYE'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'MEDUSA'), 'RANGED', 4),
((select id from creature where full_name = 'MEDUSA'), 'TWO_HEX', null),
((select id from creature where full_name = 'MEDUSA'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'MEDUSA'), 'PETRIFY', 20),
((select id from creature where full_name = 'MEDUSA_QUEEN'), 'RANGED', 8),
((select id from creature where full_name = 'MEDUSA_QUEEN'), 'TWO_HEX', null),
((select id from creature where full_name = 'MEDUSA_QUEEN'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'MEDUSA_QUEEN'), 'PETRIFY', 20),
((select id from creature where full_name = 'MINOTAUR'), 'POSITIVE_MORALE', null),
((select id from creature where full_name = 'MINOTAUR_KING'), 'POSITIVE_MORALE', null),
((select id from creature where full_name = 'MANTICORE'), 'FLYING', null),
((select id from creature where full_name = 'MANTICORE'), 'TWO_HEX', null),
((select id from creature where full_name = 'SCORPICORE'), 'FLYING', null),
((select id from creature where full_name = 'SCORPICORE'), 'TWO_HEX', null),
((select id from creature where full_name = 'SCORPICORE'), 'PARALYZE', null),
((select id from creature where full_name = 'RED_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'RED_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'RED_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'RED_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'RED_DRAGON'), 'SPELL_IMMUNE', 3),
((select id from creature where full_name = 'BLACK_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'BLACK_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'BLACK_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'BLACK_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'BLACK_DRAGON'), 'SPELL_IMMUNE', 5),
((select id from creature where full_name = 'BLACK_DRAGON'), 'HATES', (select id from creature where full_name = 'GIANT')),
((select id from creature where full_name = 'BLACK_DRAGON'), 'HATES', (select id from creature where full_name = 'TITAN')),
---------------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'WOLF_RIDER'), 'TWO_HEX', null),
((select id from creature where full_name = 'WOLF_RAIDER'), 'TWO_HEX', null),
((select id from creature where full_name = 'WOLF_RAIDER'), 'DOUBLE_ATTACK', null),
((select id from creature where full_name = 'ORC'), 'RANGED', 12),
((select id from creature where full_name = 'ORC_CHIEFTAIN'), 'RANGED', 24),
((select id from creature where full_name = 'OGRE_MAGE'), 'SPELLCASTER', null),
((select id from creature where full_name = 'ROC'), 'TWO_HEX', null),
((select id from creature where full_name = 'ROC'), 'FLYING', null),
((select id from creature where full_name = 'THUNDERBIRD'), 'TWO_HEX', null),
((select id from creature where full_name = 'THUNDERBIRD'), 'FLYING', null),
((select id from creature where full_name = 'THUNDERBIRD'), 'LIGHTNING_STRIKE', 20),
((select id from creature where full_name = 'CYCLOPS'), 'RANGED', 16),
((select id from creature where full_name = 'CYCLOPS'), 'BALLISTICS', 1),
((select id from creature where full_name = 'CYCLOPS_KING'), 'RANGED', 24),
((select id from creature where full_name = 'CYCLOPS_KING'), 'BALLISTICS', 2),
((select id from creature where full_name = 'BEHEMOTH'), 'TWO_HEX', null),
((select id from creature where full_name = 'BEHEMOTH'), 'REDUCE_DEFENSE', 40),
((select id from creature where full_name = 'ANCIENT_BEHEMOTH'), 'TWO_HEX', null),
((select id from creature where full_name = 'ANCIENT_BEHEMOTH'), 'REDUCE_DEFENSE', 80),
-------------------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'LIZARDMAN'), 'RANGED', 12),
((select id from creature where full_name = 'LIZARD_WARRIOR'), 'RANGED', 24),
((select id from creature where full_name = 'SERPENT_FLY'), 'FLYING', null),
((select id from creature where full_name = 'SERPENT_FLY'), 'DISPEL', null),
((select id from creature where full_name = 'DRAGON_FLY'), 'FLYING', null),
((select id from creature where full_name = 'DRAGON_FLY'), 'DISPEL', null),
((select id from creature where full_name = 'DRAGON_FLY'), 'WEAKNESS', 2),
((select id from creature where full_name = 'BASILISK'), 'TWO_HEX', null),
((select id from creature where full_name = 'BASILISK'), 'PETRIFY', 20),
((select id from creature where full_name = 'GREATER_BASILISK'), 'TWO_HEX', null),
((select id from creature where full_name = 'GREATER_BASILISK'), 'PETRIFY', 20),
((select id from creature where full_name = 'GORGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'MIGHTY_GORGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'MIGHTY_GORGON'), 'DEATH_STARE', 10),
((select id from creature where full_name = 'WYVERN'), 'TWO_HEX', null),
((select id from creature where full_name = 'WYVERN'), 'FLYING', null),
((select id from creature where full_name = 'WYVERN_MONARCH'), 'TWO_HEX', null),
((select id from creature where full_name = 'WYVERN_MONARCH'), 'FLYING', null),
((select id from creature where full_name = 'WYVERN_MONARCH'), 'POISON', 30),
((select id from creature where full_name = 'HYDRA'), 'TWO_HEX', null),
((select id from creature where full_name = 'HYDRA'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'HYDRA'), 'ATTACK_ADJACENT', null),
((select id from creature where full_name = 'CHAOS_HYDRA'), 'TWO_HEX', null),
((select id from creature where full_name = 'CHAOS_HYDRA'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'CHAOS_HYDRA'), 'ATTACK_ADJACENT', null),
--------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'PIXIE'), 'FLYING', null),
((select id from creature where full_name = 'SPRITE'), 'FLYING', null),
((select id from creature where full_name = 'SPRITE'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'AIR_ELEMENTAL'), 'ELEMENTAL', 1),
((select id from creature where full_name = 'AIR_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'LIGHTNING_BOLT')),
((select id from creature where full_name = 'AIR_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'CHAIN_LIGHTNING')),
((select id from creature where full_name = 'AIR_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'METEOR_SHOWER')),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'ELEMENTAL', 1),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'RANGED', 24),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'LIGHTNING_BOLT')),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'CHAIN_LIGHTNING')),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'METEOR_SHOWER')),
((select id from creature where full_name = 'STORM_ELEMENTAL'), 'SPELLCASTER', 3),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'ELEMENTAL', 4),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'TWO_HEX', null),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FIRE_WALL')),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FIREBALL')),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'INFERNO')),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'ARMAGEDDON')),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'ICE_BOLT')),
((select id from creature where full_name = 'WATER_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'FROST_RING')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'ELEMENTAL', 4),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'RANGED', 24),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'TWO_HEX', null),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FIRE_WALL')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FIREBALL')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'INFERNO')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'ARMAGEDDON')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'ICE_BOLT')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'FROST_RING')),
((select id from creature where full_name = 'ICE_ELEMENTAL'), 'SPELLCASTER', 3),
((select id from creature where full_name = 'FIRE_ELEMENTAL'), 'ELEMENTAL', 3),
((select id from creature where full_name = 'FIRE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'ICE_BOLT')),
((select id from creature where full_name = 'FIRE_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FROST_RING')),
((select id from creature where full_name = 'FIRE_ELEMENTAL'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'ELEMENTAL', 3),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'FLYING', null),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'ICE_BOLT')),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'FROST_RING')),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'ENERGY_ELEMENTAL'), 'SPELLCASTER', 3),
((select id from creature where full_name = 'EARTH_ELEMENTAL'), 'ELEMENTAL', 2),
((select id from creature where full_name = 'EARTH_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'METEOR_SHOWER')),
((select id from creature where full_name = 'EARTH_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'LIGHTNING_BOLT')),
((select id from creature where full_name = 'EARTH_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'CHAIN_LIGHTNING')),
((select id from creature where full_name = 'EARTH_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'ARMAGEDDON')),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'ELEMENTAL', 2),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'SPELLCASTER', 3),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'VULNERABLE', (select id from spell where full_name = 'METEOR_SHOWER')),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'LIGHTNING_BOLT')),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'CHAIN_LIGHTNING')),
((select id from creature where full_name = 'MAGMA_ELEMENTAL'), 'IMMUNE', (select id from spell where full_name = 'ARMAGEDDON')),
((select id from creature where full_name = 'PSYCHIC_ELEMENTAL'), 'ELEMENTAL', null),
((select id from creature where full_name = 'PSYCHIC_ELEMENTAL'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'PSYCHIC_ELEMENTAL'), 'ATTACK_ADJACENT', null),
((select id from creature where full_name = 'PSYCHIC_ELEMENTAL'), 'WEAK_AGAINST_MIND_IMMUNE', null),
((select id from creature where full_name = 'MAGIC_ELEMENTAL'), 'ELEMENTAL', null),
((select id from creature where full_name = 'MAGIC_ELEMENTAL'), 'NO_RETALIATION', null),
((select id from creature where full_name = 'MAGIC_ELEMENTAL'), 'ATTACK_ADJACENT', null),
((select id from creature where full_name = 'MAGIC_ELEMENTAL'), 'SPELL_IMMUNE', 5),
((select id from creature where full_name = 'MAGIC_ELEMENTAL'), 'WEAK_AGAINST_SPELL_IMMUNE', null),
((select id from creature where full_name = 'FIREBIRD'), 'TWO_HEX', null),
((select id from creature where full_name = 'FIREBIRD'), 'FLYING', null),
((select id from creature where full_name = 'FIREBIRD'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'FIREBIRD'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'PHOENIX'), 'TWO_HEX', null),
((select id from creature where full_name = 'PHOENIX'), 'FLYING', null),
((select id from creature where full_name = 'PHOENIX'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'PHOENIX'), 'FIRE_IMMUNITY', null),
((select id from creature where full_name = 'PHOENIX'), 'REBIRTH', 20),
----------------------------------------------------------------------------------------
((select id from creature where full_name = 'HALFLING'), 'RANGED', 24),
((select id from creature where full_name = 'HALFLING'), 'POSITIVE_LUCK', null),
((select id from creature where full_name = 'ROGUE'), 'SPYING', null),
((select id from creature where full_name = 'BOAR'), 'TWO_HEX', null),
((select id from creature where full_name = 'NOMAD'), 'SANDWALKER', null),
((select id from creature where full_name = 'NOMAD'), 'TWO_HEX', null),
((select id from creature where full_name = 'MUMMY'), 'UNDEAD', null),
((select id from creature where full_name = 'MUMMY'), 'CURSE', 25),
((select id from creature where full_name = 'SHARPSHOOTER'), 'RANGED', 32),
((select id from creature where full_name = 'SHARPSHOOTER'), 'NO_OBSTACLE_PENALTY', null),
((select id from creature where full_name = 'SHARPSHOOTER'), 'NO_RANGED_PENALTY', null),
((select id from creature where full_name = 'TROLL'), 'REGENERATION', 50),
((select id from creature where full_name = 'GOLD_GOLEM'), 'SPELL_RESISTANCE', 85),
((select id from creature where full_name = 'GOLD_GOLEM'), 'UNLIVING', null),
((select id from creature where full_name = 'DIAMOND_GOLEM'), 'SPELL_RESISTANCE', 95),
((select id from creature where full_name = 'DIAMOND_GOLEM'), 'UNLIVING', null),
((select id from creature where full_name = 'ENCHANTER'), 'RANGED', 32),
((select id from creature where full_name = 'ENCHANTER'), 'NO_MELEE_PENALTY', null),
((select id from creature where full_name = 'ENCHANTER'), 'NO_OBSTACLE_PENALTY', null),
((select id from creature where full_name = 'ENCHANTER'), 'ROUND_SPELLCASTER', 3),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'MAGIC_MIRROR', 20),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'ROLL_SPELL', null),
((select id from creature where full_name = 'FAERIE_DRAGON'), 'SPELLCASTER', 5),
((select id from creature where full_name = 'RUST_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'RUST_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'RUST_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'RUST_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'RUST_DRAGON'), 'ACID_BREATH', 20),
((select id from creature where full_name = 'CRYSTAL_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'CRYSTAL_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'CRYSTAL_DRAGON'), 'MAGIC_RESISTANCE', 20),
((select id from creature where full_name = 'CRYSTAL_DRAGON'), 'CRYSTAL_GENERATION', null),
((select id from creature where full_name = 'AZURE_DRAGON'), 'TWO_HEX', null),
((select id from creature where full_name = 'AZURE_DRAGON'), 'FLYING', null),
((select id from creature where full_name = 'AZURE_DRAGON'), 'DRAGON', null),
((select id from creature where full_name = 'AZURE_DRAGON'), 'SPELL_IMMUNE', 3),
((select id from creature where full_name = 'AZURE_DRAGON'), 'BREATH_ATTACK', null),
((select id from creature where full_name = 'AZURE_DRAGON'), 'FEAR', 20),
((select id from creature where full_name = 'AZURE_DRAGON'), 'IMMUNE_TO_FEAR', null),
------------------------------------------------------------------------------------------------------------
((select id from creature where full_name = 'AMMO_CART'), 'WAR_MACHINE', 1),
((select id from creature where full_name = 'AMMO_CART'), 'INFINITE_SHOTS', null),
((select id from creature where full_name = 'BALLISTA'), 'WAR_MACHINE', 2),
((select id from creature where full_name = 'BALLISTA'), 'TWO_HEX', null),
((select id from creature where full_name = 'BALLISTA'), 'ARTILLERY', null),
((select id from creature where full_name = 'BALLISTA'), 'RANGED', 9999),
((select id from creature where full_name = 'CATAPULT'), 'WAR_MACHINE', 3),
((select id from creature where full_name = 'CATAPULT'), 'TWO_HEX', null),
((select id from creature where full_name = 'CATAPULT'), 'BALLISTICS', null),
((select id from creature where full_name = 'FIRST_AID_TENT'), 'WAR_MACHINE', 4),
((select id from creature where full_name = 'FIRST_AID_TENT'), 'TWO_HEX', null),
((select id from creature where full_name = 'FIRST_AID_TENT'), 'FIRST_AID', null);
