create table specific_creature_specialty (
id int4 not null primary key,
full_name varchar not null,
attack_bonus int4 not null,
defense_bonus int4 not null,
damage_bonus int4 not null,
speed_bonus int4 not null
);

insert into specific_creature_specialty (
id, full_name, attack_bonus, defense_bonus, damage_bonus, speed_bonus
) values
(0, 'DEATH_KNIGHT_BONUS', 5, 5, 10, 0),
(1, 'SHARPSHOOTER_BONUS', 0, 0, 0, 0),
(2, 'ENCHANTER_BONUS', 0, 0, 0, 0),
(3, 'DRAGON_BONUS', 5, 5, 0, 0),
(4, 'BEHEMOTH_BONUS', 5, 5, 10, 0),
(5, 'EARTH_ELEMENTAL_BONUS', 2, 1, 5, 0),
(6, 'FIRE_ELEMENTAL_BONUS', 1, 2, 2, 0),
(7, 'WATER_ELEMENTAL_BONUS', 2, 0, 0, 0),
(8, 'PSYCHIC_ELEMENTAL_BONUS', 3, 3, 0, 0),
(9, 'DEVIL_BONUS', 4, 2, 0, 1);

create table hero (
id int4 not null primary key,
full_name varchar not null,
hero_type_id int4 not null,
male boolean not null,
specialty_type int4 not null,
specialty_id int4 not null,
spell_id int4,
CONSTRAINT fk_hero_type FOREIGN KEY(hero_type_id) REFERENCES hero_type(id),
CONSTRAINT fk_spell FOREIGN KEY(spell_id) REFERENCES spell(id)
);

insert into hero (
id, full_name, hero_type_id, male, specialty_type, specialty_id, spell_id
) values
(0,'CHRISTIAN',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,10,5,null),
(1,'EDRIC',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'GRIFFIN'),null),
(2,'ORRIN',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),null),
(3,'SYLVIA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),null),
(4,'VALESKA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'ARCHER'),null),
(5,'SORSHA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(6,'TYRIS',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'CAVALIER'),null),
(7,'LORD_HAART',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),null),
(144,'CATHERINE',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(145,'ROLAND',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(146,'SIR_MULLICH',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,9,2,null),
(8,'ADELA',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,3,(SELECT id FROM spell WHERE full_name = 'BLESS'),(SELECT id FROM spell WHERE full_name = 'BLESS')),
(9,'ADELAIDE',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,3,(SELECT id FROM spell WHERE full_name = 'FROST_RING'),(SELECT id FROM spell WHERE full_name = 'FROST_RING')),
(10,'CAITLIN',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,4,350,(SELECT id FROM spell WHERE full_name = 'CURE')),
(11,'CUTHBERT',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(12,'INGHAM',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,1,(SELECT id FROM creature WHERE full_name = 'MONK'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(13,'LOYNIS',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,3,(SELECT id FROM spell WHERE full_name = 'PRAYER'),(SELECT id FROM spell WHERE full_name = 'PRAYER')),
(14,'RION',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(15,'SANYA',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(16,'JENOVA',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,4,350,null),
(17,'KYRRE',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),null),
(18,'IVOR',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'WOOD_ELF'),null),
(19,'UFRETIN',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'DWARF'),null),
(20,'CLANCY',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'UNICORN'),null),
(21,'THORGRIM',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),null),
(22,'RYLAND',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'DENDROID_GUARD'),null),
(23,'MEPHALA',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),null),
(147,'GELU',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'SHARPSHOOTER_BONUS'),null),
(24,'AERIS',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,1,(SELECT id FROM creature WHERE full_name = 'PEGASUS'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(25,'ALAGAR',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'ICE_BOLT'),(SELECT id FROM spell WHERE full_name = 'ICE_BOLT')),
(26,'CORONIUS',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'SLAYER'),(SELECT id FROM spell WHERE full_name = 'SLAYER')),
(27,'ELLESHAR',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(28,'MALCOM',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(29,'MELODIA',(SELECT id FROM hero_type WHERE full_name ='DRUID'),false,3,(SELECT id FROM spell WHERE full_name = 'FORTUNE'),(SELECT id FROM spell WHERE full_name = 'FORTUNE')),
(30,'GEM',(SELECT id FROM hero_type WHERE full_name ='DRUID'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'SUMMON_BOAT')),
(31,'ULAND',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'CURE'),(SELECT id FROM spell WHERE full_name = 'CURE')),
(32,'FAFNER',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'NAGA'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(33,'IONA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,1,(SELECT id FROM creature WHERE full_name = 'GENIE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(34,'JOSEPHINE',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,1,(SELECT id FROM creature WHERE full_name = 'STONE_GOLEM'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(35,'NEELA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(36,'PIQUEDRAM',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'STONE_GARGOYLE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(37,'RISSA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,6,1,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(38,'THANE',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'GENIE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(39,'TOROSAR',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,10,5,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(40,'AINE',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,4,350,(SELECT id FROM spell WHERE full_name = 'CURSE')),
(41,'ASTRAL',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,3,(SELECT id FROM spell WHERE full_name = 'HYPNOTIZE'),(SELECT id FROM spell WHERE full_name = 'HYPNOTIZE')),
(42,'CYRA',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(43,'DAREMYTH',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,3,(SELECT id FROM spell WHERE full_name = 'FORTUNE'),(SELECT id FROM spell WHERE full_name = 'FORTUNE')),
(44,'HALON',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(45,'SERENA',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(46,'SOLMYR',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,3,(SELECT id FROM spell WHERE full_name = 'CHAIN_LIGHTNING'),(SELECT id FROM spell WHERE full_name = 'CHAIN_LIGHTNING')),
(47,'THEODORUS',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,1,(SELECT id FROM creature WHERE full_name = 'MAGE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(148,'DRACON',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'ENCHANTER_BONUS'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(48,'CALH',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,1,(SELECT id FROM creature WHERE full_name = 'GOG'),null),
(49,'FIONA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'HELL_HOUND'),null),
(50,'IGNATIUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,1,(SELECT id FROM creature WHERE full_name = 'IMP'),null),
(51,'MARIUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'DEMON'),null),
(52,'NYMUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'PIT_FIEND'),null),
(53,'OCTAVIA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,4,350,null),
(54,'PYRE',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,10,5,null),
(55,'RASHKA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'EFREET'),null),
(149,'XERON',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DEVIL_BONUS'),null),
(56,'ASH',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,3,(SELECT id FROM spell WHERE full_name = 'BLOODLUST'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(57,'AXSIS',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(58,'AYDEN',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'VIEW_EARTH')),
(59,'CALID',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,7,1,(SELECT id FROM spell WHERE full_name = 'HASTE')),
(60,'OLEMA',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(61,'XYRON',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,3,(SELECT id FROM spell WHERE full_name = 'INFERNO'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(62,'XARFAX',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,3,(SELECT id FROM spell WHERE full_name = 'FIREBALL'),(SELECT id FROM spell WHERE full_name = 'FIREBALL')),
(63,'ZYDAR',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(64,'CHARNA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'WIGHT'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(65,'CLAVIUS',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,4,350,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(66,'GALTHRAN',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'SKELETON'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(67,'ISRA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(68,'MOANDOR',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'LICH'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(69,'STRAKER',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'WALKING_DEAD'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(70,'TAMIKA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'BLACK_KNIGHT'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(71,'VOKIAL',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'VAMPIRE'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(155,'LORD_HAART_DEATH_KNIGHT',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DEATH_KNIGHT_BONUS'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(72,'AISLINN',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER'),(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER')),
(73,'NAGASH',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,4,350,(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(74,'NIMBUS',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(75,'SANDRO',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(76,'SEPTIENNA',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'DEATH_RIPPLE'),(SELECT id FROM spell WHERE full_name = 'DEATH_RIPPLE')),
(77,'THANT',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,3,(SELECT id FROM spell WHERE full_name = 'ANIMATE_DEAD'),(SELECT id FROM spell WHERE full_name = 'ANIMATE_DEAD')),
(78,'VIDOMINA',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(79,'XSI',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(80,'AJIT',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'BEHOLDER'),null),
(81,'ARLACH',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,10,5,null),
(82,'DACE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'MINOTAUR'),null),
(83,'DAMACON',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,4,350,null),
(84,'GUNNAR',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),null),
(85,'LORELEI',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,1,(SELECT id FROM creature WHERE full_name = 'HARPY'),null),
(86,'SHAKTI',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'TROGLODYTE'),null),
(87,'SYNCA',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,1,(SELECT id FROM creature WHERE full_name = 'MANTICORE'),null),
(150,'MUTARE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DRAGON_BONUS'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(151,'MUTARE_DRAKE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DRAGON_BONUS'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(88,'ALAMAR',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'RESURRECTION'),(SELECT id FROM spell WHERE full_name = 'RESURRECTION')),
(89,'DARKSTORN',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(90,'DEEMER',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER'),(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER')),
(91,'GEON',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(92,'JAEGAR',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(93,'JEDDITE',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'RESURRECTION'),(SELECT id FROM spell WHERE full_name = 'RESURRECTION')),
(94,'MALEKITH',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(95,'SEPHINROTH',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),false,5,1,(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(96,'CRAG_HACK',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),null),
(97,'GRETCHIN',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),false,1,(SELECT id FROM creature WHERE full_name = 'GOBLIN'),null),
(98,'GURNISSON',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,10,5,null),
(99,'JABARKAS',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'ORC'),null),
(100,'KRELLION',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),null),
(101,'SHIVA',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),false,1,(SELECT id FROM creature WHERE full_name = 'ROC'),null),
(102,'TYRAXOR',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'WOLF_RIDER'),null),
(103,'YOG',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'CYCLOPS'),null),
(152,'BORAGUS',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),null),
(153,'KILGOR',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'BEHEMOTH_BONUS'),null),
(104,'DESSA',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(105,'GIRD',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(106,'GUNDULA',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(107,'ORIS',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(108,'SAURUG',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,8,1,(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(109,'TEREK',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(110,'VEY',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(111,'ZUBIN',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,3,(SELECT id FROM spell WHERE full_name = 'PRECISION'),(SELECT id FROM spell WHERE full_name = 'PRECISION')),
(112,'ALKIN',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'GORGON'),null),
(113,'BROGHILD',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'WYVERN'),null),
(114,'BRON',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'BASILISK'),null),
(115,'DRAKON',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'GNOLL'),null),
(116,'GERWULF',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,10,5,null),
(117,'KORBAC',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'SERPENT_FLY'),null),
(118,'TAZAR',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),null),
(119,'WYSTAN',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'LIZARDMAN'),null),
(120,'ANDRA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(121,'MERIST',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(122,'MIRLANDA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(123,'ROSIC',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(124,'STYG',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(125,'TIVA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(126,'VERDISH',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_FIRE')),
(127,'VOY',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(154,'ADRIENNE',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(128,'ERDAMON',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'EARTH_ELEMENTAL_BONUS'),null),
(129,'FIUR',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'FIRE_ELEMENTAL_BONUS'),null),
(130,'IGNISSA',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'FIRE_ELEMENTAL_BONUS'),null),
(131,'KALT',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'WATER_ELEMENTAL_BONUS'),null),
(132,'LACUS',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'WATER_ELEMENTAL_BONUS'),null),
(133,'MONERE',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'PSYCHIC_ELEMENTAL_BONUS'),null),
(134,'PASIS',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'PSYCHIC_ELEMENTAL_BONUS'),null),
(135,'THUNAR',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'EARTH_ELEMENTAL_BONUS'),null),
(136,'AENAIN',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,3,(SELECT id FROM spell WHERE full_name = 'DISRUPTING_RAY'),(SELECT id FROM spell WHERE full_name = 'DISRUPTING_RAY')),
(137,'BRISSA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(138,'CIELE',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(139,'GELARE',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,4,350,(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(140,'GRINDAN',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,4,350,(SELECT id FROM spell WHERE full_name = 'SLOW')),
(141,'INTEUS',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,3,(SELECT id FROM spell WHERE full_name = 'BLOODLUST'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(142,'LABETHA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(143,'LUNA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'FIRE_WALL'),(SELECT id FROM spell WHERE full_name = 'FIRE_WALL'));

create table hero_to_skill (
id serial primary key,
hero_id int4 not null,
lvl int4 not null,
skill_id int4 not null,
CONSTRAINT fk_hero FOREIGN KEY(hero_id) REFERENCES hero(id),
CONSTRAINT fk_skill FOREIGN KEY(skill_id) REFERENCES secondary_skill(id)
);

insert into hero_to_skill (
hero_id, lvl, skill_id
) values
((SELECT id FROM hero WHERE full_name = 'CHRISTIAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'CHRISTIAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'EDRIC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'EDRIC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'ORRIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'ORRIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'SYLVIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'SYLVIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION')),
((SELECT id FROM hero WHERE full_name = 'VALESKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'VALESKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'SORSHA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'SORSHA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'TYRIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'TYRIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'CATHERINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'CATHERINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'ROLAND'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'ROLAND'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'SIR_MULLICH'),2,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'ADELA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ADELA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY')),
((SELECT id FROM hero WHERE full_name = 'ADELAIDE'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CAITLIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CAITLIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'CUTHBERT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CUTHBERT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'INGHAM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'INGHAM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'LOYNIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'LOYNIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'RION'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'RION'),1,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID')),
((SELECT id FROM hero WHERE full_name = 'SANYA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'SANYA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'JENOVA'),2,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'KYRRE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'KYRRE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS')),
((SELECT id FROM hero WHERE full_name = 'IVOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'IVOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'UFRETIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'UFRETIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LUCK')),
((SELECT id FROM hero WHERE full_name = 'CLANCY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'CLANCY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING')),
((SELECT id FROM hero WHERE full_name = 'THORGRIM'),2,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'RYLAND'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'RYLAND'),1,(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY')),
((SELECT id FROM hero WHERE full_name = 'MEPHALA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'MEPHALA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'GELU'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'GELU'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'AERIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'AERIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'ALAGAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ALAGAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'CORONIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CORONIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'ELLESHAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ELLESHAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'MALCOM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'MALCOM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'MELODIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'MELODIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LUCK')),
((SELECT id FROM hero WHERE full_name = 'GEM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GEM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID')),
((SELECT id FROM hero WHERE full_name = 'ULAND'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ULAND'),1,(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS')),
((SELECT id FROM hero WHERE full_name = 'FAFNER'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'FAFNER'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'IONA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'IONA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'JOSEPHINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'JOSEPHINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'NEELA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'NEELA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'PIQUEDRAM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'PIQUEDRAM'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'RISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'RISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'THANE'),2,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'TOROSAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'TOROSAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'AINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'AINE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'ASTRAL'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CYRA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CYRA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY')),
((SELECT id FROM hero WHERE full_name = 'DAREMYTH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'DAREMYTH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'HALON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'HALON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'SERENA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'SERENA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'SOLMYR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'SOLMYR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'THEODORUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'THEODORUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS')),
((SELECT id FROM hero WHERE full_name = 'DRACON'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CALH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'CALH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'FIONA'),2,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'IGNATIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'IGNATIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'MARIUS'),2,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'NYMUS'),2,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'OCTAVIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'OCTAVIA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'PYRE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS')),
((SELECT id FROM hero WHERE full_name = 'PYRE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'RASHKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'RASHKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'XERON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'XERON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'ASH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ASH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'AXSIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'AXSIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'AYDEN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'AYDEN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'CALID'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CALID'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'OLEMA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'OLEMA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS')),
((SELECT id FROM hero WHERE full_name = 'XYRON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'XYRON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'XARFAX'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'XARFAX'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'ZYDAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ZYDAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'CHARNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'CHARNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'CLAVIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'CLAVIUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'GALTHRAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'GALTHRAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'ISRA'),2,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'MOANDOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'MOANDOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'STRAKER'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'STRAKER'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'TAMIKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'TAMIKA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'VOKIAL'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'VOKIAL'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART_DEATH_KNIGHT'),2,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'AISLINN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'AISLINN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'NAGASH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'NAGASH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'NIMBUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'NIMBUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'SANDRO'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'SANDRO'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'SEPTIENNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'SEPTIENNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'THANT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'THANT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'VIDOMINA'),2,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'XSI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY')),
((SELECT id FROM hero WHERE full_name = 'XSI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'AJIT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'AJIT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'ARLACH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'ARLACH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'DACE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'DACE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'DAMACON'),2,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'GUNNAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'GUNNAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS')),
((SELECT id FROM hero WHERE full_name = 'LORELEI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'LORELEI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'SHAKTI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'SHAKTI'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'SYNCA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'SYNCA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'MUTARE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'MUTARE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'MUTARE_DRAKE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'MUTARE_DRAKE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'ALAMAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ALAMAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR')),
((SELECT id FROM hero WHERE full_name = 'DARKSTORN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'DARKSTORN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'DEEMER'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'DEEMER'),2,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'GEON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GEON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'JAEGAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'JAEGAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'JEDDITE'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'MALEKITH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'MALEKITH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'SEPHINROTH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'SEPHINROTH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'CRAG_HACK'),2,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'GRETCHIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'GRETCHIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING')),
((SELECT id FROM hero WHERE full_name = 'GURNISSON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'GURNISSON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'JABARKAS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'JABARKAS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'KRELLION'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'KRELLION'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'SHIVA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'SHIVA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'TYRAXOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'TYRAXOR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'YOG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'YOG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS')),
((SELECT id FROM hero WHERE full_name = 'BORAGUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'BORAGUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'KILGOR'),2,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'DESSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'DESSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS')),
((SELECT id FROM hero WHERE full_name = 'GIRD'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GIRD'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'GUNDULA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GUNDULA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'ORIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ORIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'SAURUG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'SAURUG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'TEREK'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'TEREK'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'VEY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'VEY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'ZUBIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ZUBIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'ALKIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'ALKIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'BROGHILD'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'BROGHILD'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING')),
((SELECT id FROM hero WHERE full_name = 'BRON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'BRON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE')),
((SELECT id FROM hero WHERE full_name = 'DRAKON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'DRAKON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP')),
((SELECT id FROM hero WHERE full_name = 'GERWULF'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'GERWULF'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'KORBAC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'KORBAC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING')),
((SELECT id FROM hero WHERE full_name = 'TAZAR'),2,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'WYSTAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER')),
((SELECT id FROM hero WHERE full_name = 'WYSTAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY')),
((SELECT id FROM hero WHERE full_name = 'ANDRA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ANDRA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE')),
((SELECT id FROM hero WHERE full_name = 'MERIST'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'MERIST'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'MIRLANDA'),2,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ROSIC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ROSIC'),1,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM')),
((SELECT id FROM hero WHERE full_name = 'STYG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'STYG'),1,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY')),
((SELECT id FROM hero WHERE full_name = 'TIVA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'TIVA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE')),
((SELECT id FROM hero WHERE full_name = 'VERDISH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'VERDISH'),1,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID')),
((SELECT id FROM hero WHERE full_name = 'VOY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'VOY'),1,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION')),
((SELECT id FROM hero WHERE full_name = 'ADRIENNE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'ADRIENNE'),3,(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'ERDAMON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'ERDAMON'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'FIUR'),2,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'IGNISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'IGNISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'KALT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'KALT'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING')),
((SELECT id FROM hero WHERE full_name = 'LACUS'),2,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'MONERE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'MONERE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS')),
((SELECT id FROM hero WHERE full_name = 'PASIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE')),
((SELECT id FROM hero WHERE full_name = 'PASIS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY')),
((SELECT id FROM hero WHERE full_name = 'THUNAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS')),
((SELECT id FROM hero WHERE full_name = 'THUNAR'),1,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES')),
((SELECT id FROM hero WHERE full_name = 'AENAIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'AENAIN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'BRISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'BRISSA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'CIELE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'CIELE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'GELARE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GELARE'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'GRINDAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'GRINDAN'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'INTEUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'INTEUS'),1,(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'LABETHA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'LABETHA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC')),
((SELECT id FROM hero WHERE full_name = 'LUNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM')),
((SELECT id FROM hero WHERE full_name = 'LUNA'),1,(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'));

CREATE TABLE public.creature_to_specific (
	id serial primary key,
	specialty_id int4 not null,
	creature_id int4 not null
);

INSERT INTO public.creature_to_specific (
    specialty_id, creature_id
) values
((select id from specific_creature_specialty where full_name = 'DEATH_KNIGHT_BONUS'), (select id from creature where full_name = 'BLACK_KNIGHT')),
((select id from specific_creature_specialty where full_name = 'DEATH_KNIGHT_BONUS'), (select id from creature where full_name = 'DREAD_KNIGHT')),
((select id from specific_creature_specialty where full_name = 'BEHEMOTH_BONUS'), (select id from creature where full_name = 'BEHEMOTH')),
((select id from specific_creature_specialty where full_name = 'BEHEMOTH_BONUS'), (select id from creature where full_name = 'ANCIENT_BEHEMOTH')),
((select id from specific_creature_specialty where full_name = 'EARTH_ELEMENTAL_BONUS'), (select id from creature where full_name = 'EARTH_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'EARTH_ELEMENTAL_BONUS'), (select id from creature where full_name = 'MAGMA_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'FIRE_ELEMENTAL_BONUS'), (select id from creature where full_name = 'FIRE_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'FIRE_ELEMENTAL_BONUS'), (select id from creature where full_name = 'ENERGY_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'WATER_ELEMENTAL_BONUS'), (select id from creature where full_name = 'WATER_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'WATER_ELEMENTAL_BONUS'), (select id from creature where full_name = 'ICE_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'PSYCHIC_ELEMENTAL_BONUS'), (select id from creature where full_name = 'PSYCHIC_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'PSYCHIC_ELEMENTAL_BONUS'), (select id from creature where full_name = 'MAGIC_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'DEVIL_BONUS'), (select id from creature where full_name = 'DEVIL')),
((select id from specific_creature_specialty where full_name = 'DEVIL_BONUS'), (select id from creature where full_name = 'ARCH_DEVIL')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GREEN_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GOLD_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'RED_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'BLACK_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'BONE_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GHOST_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'AZURE_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'CRYSTAL_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'RUST_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'FAERIE_DRAGON'));

-- drop table hero_to_skill;
-- drop table hero;
-- drop table specific_creature_specialty;
-- drop table public.creature__to_specific;