create table terrain_type (
id int4 NOT null primary key,
full_name varchar not null,
movement int4 not null
);

insert into terrain_type (
id, full_name, movement
) values
(0, 'GRASS', 100),
(1, 'DIRT', 100),
(2, 'LAVA', 100),
(3, 'SUBTERRANEAN', 100),
(4, 'ROUGH', 125),
(5, 'SAND', 150),
(6, 'SNOW', 150),
(7, 'SWAMP', 175);

create table castle (
id int4 not null primary key,
full_name varchar not null,
terrain_id int4 not null,
CONSTRAINT fk_terrain FOREIGN KEY(terrain_id) REFERENCES terrain_type(id)
);

insert into castle (
id, full_name, terrain_id
) values
(0, 'CASTLE', (SELECT id FROM terrain_type WHERE full_name = 'GRASS')),
(1, 'RAMPART', (SELECT id FROM terrain_type WHERE full_name = 'GRASS')),
(2, 'TOWER', (SELECT id FROM terrain_type WHERE full_name = 'SNOW')),
(3, 'INFERNO', (SELECT id FROM terrain_type WHERE full_name = 'LAVA')),
(4, 'NECROPOLIS', (SELECT id FROM terrain_type WHERE full_name = 'DIRT')),
(5, 'DUNGEON', (SELECT id FROM terrain_type WHERE full_name = 'SUBTERRANEAN')),
(6, 'STRONGHOLD', (SELECT id FROM terrain_type WHERE full_name = 'ROUGH')),
(7, 'FORTRESS', (SELECT id FROM terrain_type WHERE full_name = 'SWAMP')),
(8, 'CONFLUX', (SELECT id FROM terrain_type WHERE full_name = 'GRASS'));

create table hero_type (
id int4 not null primary key,
full_name varchar not null,
castle_id int4 not null,
book boolean not null,
mage boolean not null,
base_attack int4 not null,
base_defense int4 not null,
base_spell_power int4 not null,
base_knowledge int4 not null,
attack_probability_low int4 not null,
defense_probability_low int4 not null,
spell_power_probability_low int4 not null,
knowledge_probability_low int4 not null,
attack_probability_high int4 not null,
defense_probability_high int4 not null,
spell_power_probability_high int4 not null,
knowledge_probability_high int4 not null,
CONSTRAINT fk_castle FOREIGN KEY(castle_id) REFERENCES castle(id)
);

insert into hero_type (
id, full_name, castle_id, book, mage, base_attack, base_defense, base_spell_power, base_knowledge,
attack_probability_low, defense_probability_low, spell_power_probability_low, knowledge_probability_low,
attack_probability_high, defense_probability_high, spell_power_probability_high, knowledge_probability_high
) values
(0,'KNIGHT',(SELECT id FROM castle WHERE full_name = 'CASTLE'),false,false,2,2,1,1,35, 45, 10, 10, 30, 30, 20, 20),
(1,'CLERIC',(SELECT id FROM castle WHERE full_name = 'CASTLE'),true,true,1,0,2,2,20, 15, 30, 35, 20, 20, 30, 30),
(2,'RANGER',(SELECT id FROM castle WHERE full_name = 'RAMPART'),false,false,1,3,1,1,35, 45, 10, 10, 30, 30, 20, 20),
(3,'DRUID',(SELECT id FROM castle WHERE full_name = 'RAMPART'),true,true,0,2,1,2,10, 20, 35, 35, 20, 20, 30, 30),
(4,'ALCHEMIST',(SELECT id FROM castle WHERE full_name = 'TOWER'),true,false,1,1,2,2,30, 30, 20, 20, 30, 30, 20, 20),
(5,'WIZARD',(SELECT id FROM castle WHERE full_name = 'TOWER'),true,true,0,0,2,3,10, 10, 40, 40, 30, 20, 20, 30),
(6,'DEMONIAC',(SELECT id FROM castle WHERE full_name = 'INFERNO'),false,false,2,2,1,1,35, 35, 15, 15, 30, 30, 20, 20),
(7,'HERETIC',(SELECT id FROM castle WHERE full_name = 'INFERNO'),true,true,1,1,2,1,15, 15, 35, 35, 20, 20, 30, 30),
(8,'DEATH_KNIGHT',(SELECT id FROM castle WHERE full_name = 'NECROPOLIS'),true,false,1,2,2,1,30, 25, 20, 25, 25, 25, 25, 25),
(9,'NECROMANCER',(SELECT id FROM castle WHERE full_name = 'NECROPOLIS'),true,true,1,0,2,2,15, 15, 35, 35, 25, 25, 25, 25),
(10,'OVERLORD',(SELECT id FROM castle WHERE full_name = 'DUNGEON'),false,false,2,2,1,1,35, 35, 15, 15, 30, 30, 20, 20),
(11,'WARLOCK',(SELECT id FROM castle WHERE full_name = 'DUNGEON'),true,true,0,0,3,2,10, 10, 50, 30, 20, 20, 30, 30),
(12,'BARBARIAN',(SELECT id FROM castle WHERE full_name = 'STRONGHOLD'),false,false,4,0,1,1,55, 35, 5, 5, 30, 30, 20, 20),
(13,'BATTLE_MAGE',(SELECT id FROM castle WHERE full_name = 'STRONGHOLD'),true,true,2,1,1,1,30, 20, 25, 25, 25, 25, 25, 25),
(14,'BEASTMASTER',(SELECT id FROM castle WHERE full_name = 'FORTRESS'),false,false,0,4,1,1,30, 50, 10, 10, 30, 30, 20, 20),
(15,'WITCH',(SELECT id FROM castle WHERE full_name = 'FORTRESS'),true,true,0,1,2,2,5, 15, 40, 40, 20, 20, 30, 30),
(16,'PLANESWALKER',(SELECT id FROM castle WHERE full_name = 'CONFLUX'),false,false,3,1,1,1,45, 25, 15, 15, 30, 30, 20, 20),
(17,'ELEMENTALIST',(SELECT id FROM castle WHERE full_name = 'CONFLUX'),true,true,0,0,3,3,15, 15, 35, 35, 25, 25, 25, 25);

create table hero_to_secondary (
id serial primary key,
hero_type_id int4 not null,
skill_id int4 not null,
frequency int4 not null,
CONSTRAINT fk_hero_type FOREIGN KEY(hero_type_id) REFERENCES hero_type(id),
CONSTRAINT fk_skill FOREIGN KEY(skill_id) REFERENCES secondary_skill(id)
);

insert into hero_to_secondary (
hero_type_id, skill_id, frequency
) values
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),5),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),2),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),10),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),3),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),7),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),2),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),3),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),2),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),6),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),8),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),3),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),3),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),10),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),5),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),6),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),7),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),7),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),6),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),5),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),2),
((SELECT id FROM hero_type WHERE full_name = 'CLERIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),8),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),6),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),6),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),5),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),9),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),2),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),0),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),2),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),2),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),3),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),7),
((SELECT id FROM hero_type WHERE full_name = 'RANGER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),7),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),3),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),7),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),2),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),9),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),1),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),1),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),7),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),6),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),8),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),8),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),7),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),2),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),5),
((SELECT id FROM hero_type WHERE full_name = 'DRUID'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),8),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),2),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),6),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),6),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),10),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),3),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'ALCHEMIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),1),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),7),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),1),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),0),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),1),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),10),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),8),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),9),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),10),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),6),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),8),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),5),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),2),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),1),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),2),
((SELECT id FROM hero_type WHERE full_name = 'WIZARD'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),7),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),8),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),10),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEMONIAC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),5),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),5),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),2),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),3),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),10),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),5),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),8),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),5),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),3),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),2),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),3),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),2),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'HERETIC'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),0),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),0),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),1),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),7),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),6),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),2),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),0),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),8),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),10),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'DEATH_KNIGHT'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),4),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),2),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),3),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),0),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),0),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),1),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),3),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),2),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),6),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),6),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),8),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),8),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),7),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),5),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),10),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),6),
((SELECT id FROM hero_type WHERE full_name = 'NECROMANCER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),6),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),1),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),8),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),1),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),8),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),10),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),3),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),3),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),0),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),3),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),2),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),4),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),4),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),5),
((SELECT id FROM hero_type WHERE full_name = 'OVERLORD'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),5),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),1),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),6),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),3),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),1),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),0),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),1),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),8),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),8),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),8),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),10),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),10),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),5),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),5),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),8),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),5),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),4),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),2),
((SELECT id FROM hero_type WHERE full_name = 'WARLOCK'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),7),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),6),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),1),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),5),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),3),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),10),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),6),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),3),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),0),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),1),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),2),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),8),
((SELECT id FROM hero_type WHERE full_name = 'BARBARIAN'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),8),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),8),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),5),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),6),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),6),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),3),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),5),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),1),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),9),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),0),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),4),
((SELECT id FROM hero_type WHERE full_name = 'BATTLE_MAGE'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),4),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),7),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),10),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),7),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),6),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),5),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),5),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),5),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),6),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),2),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),2),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),0),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),1),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),8),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),8),
((SELECT id FROM hero_type WHERE full_name = 'BEASTMASTER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),7),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),4),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),8),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),1),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),4),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),2),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),0),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),1),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),7),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),8),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),7),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),8),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),2),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),10),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),1),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),3),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),6),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),2),
((SELECT id FROM hero_type WHERE full_name = 'WITCH'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),5),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),1),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),3),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),9),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),1),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),3),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),1),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),3),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),2),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),8),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),5),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),6),
((SELECT id FROM hero_type WHERE full_name = 'PLANESWALKER'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),6),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),2),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),1),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'),1),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'),4),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),4),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'),3),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LUCK'),2),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),1),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),0),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'),1),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'),6),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'),6),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),6),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'),6),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'),4),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),8),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),3),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'),4),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),2),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),4),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),0),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'),2),
((SELECT id FROM hero_type WHERE full_name = 'ELEMENTALIST'),(SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'),2);

-- drop table hero_to_secondary;
-- drop table hero_type;
-- drop table castle;
-- drop table terrain_type;