create table specific_creature_specialty (
id int4 not null primary key,
full_name varchar not null,
attack_bonus int4 not null,
defense_bonus int4 not null,
damage_bonus int4 not null,
speed_bonus int4 not null
);

insert into specific_creature_specialty (
id, full_name, attack_bonus, defense_bonus, damage_bonus, speed_bonus
) values
(0, 'DEATH_KNIGHT_BONUS', 5, 5, 10, 0),
(1, 'SHARPSHOOTER_BONUS', 0, 0, 0, 0),
(2, 'ENCHANTER_BONUS', 0, 0, 0, 0),
(3, 'DRAGON_BONUS', 5, 5, 0, 0),
(4, 'BEHEMOTH_BONUS', 5, 5, 10, 0),
(5, 'EARTH_ELEMENTAL_BONUS', 2, 1, 5, 0),
(6, 'FIRE_ELEMENTAL_BONUS', 1, 2, 2, 0),
(7, 'WATER_ELEMENTAL_BONUS', 2, 0, 0, 0),
(8, 'PSYCHIC_ELEMENTAL_BONUS', 3, 3, 0, 0),
(9, 'DEVIL_BONUS', 4, 2, 0, 1);

create table hero (
id int4 not null primary key,
full_name varchar not null,
hero_type_id int4 not null,
male boolean not null,
specialty_type int4 not null,
specialty_id int4 not null,
spell_id int4,
CONSTRAINT fk_hero_type FOREIGN KEY(hero_type_id) REFERENCES hero_type(id),
CONSTRAINT fk_spell FOREIGN KEY(spell_id) REFERENCES spell(id)
);

insert into hero (
id, full_name, hero_type_id, male, specialty_type, specialty_id, spell_id
) values
(0,'CHRISTIAN',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,10,5,null),
(1,'EDRIC',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'GRIFFIN'),null),
(2,'ORRIN',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'),null),
(3,'SYLVIA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),null),
(4,'VALESKA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'ARCHER'),null),
(5,'SORSHA',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(6,'TYRIS',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'CAVALIER'),null),
(7,'LORD_HAART',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'),null),
(144,'CATHERINE',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(145,'ROLAND',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'SWORDSMAN'),null),
(146,'SIR_MULLICH',(SELECT id FROM hero_type WHERE full_name ='KNIGHT'),true,9,2,null),
(8,'ADELA',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,3,(SELECT id FROM spell WHERE full_name = 'BLESS'),(SELECT id FROM spell WHERE full_name = 'BLESS')),
(9,'ADELAIDE',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,3,(SELECT id FROM spell WHERE full_name = 'FROST_RING'),(SELECT id FROM spell WHERE full_name = 'FROST_RING')),
(10,'CAITLIN',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,4,350,(SELECT id FROM spell WHERE full_name = 'CURE')),
(11,'CUTHBERT',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(12,'INGHAM',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,1,(SELECT id FROM creature WHERE full_name = 'MONK'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(13,'LOYNIS',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,3,(SELECT id FROM spell WHERE full_name = 'PRAYER'),(SELECT id FROM spell WHERE full_name = 'PRAYER')),
(14,'RION',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(15,'SANYA',(SELECT id FROM hero_type WHERE full_name ='CLERIC'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(16,'JENOVA',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,4,350,null),
(17,'KYRRE',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),null),
(18,'IVOR',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'WOOD_ELF'),null),
(19,'UFRETIN',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'DWARF'),null),
(20,'CLANCY',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'UNICORN'),null),
(21,'THORGRIM',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'),null),
(22,'RYLAND',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,1,(SELECT id FROM creature WHERE full_name = 'DENDROID_GUARD'),null),
(23,'MEPHALA',(SELECT id FROM hero_type WHERE full_name ='RANGER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),null),
(147,'GELU',(SELECT id FROM hero_type WHERE full_name ='RANGER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'SHARPSHOOTER_BONUS'),null),
(24,'AERIS',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,1,(SELECT id FROM creature WHERE full_name = 'PEGASUS'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(25,'ALAGAR',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'ICE_BOLT'),(SELECT id FROM spell WHERE full_name = 'ICE_BOLT')),
(26,'CORONIUS',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'SLAYER'),(SELECT id FROM spell WHERE full_name = 'SLAYER')),
(27,'ELLESHAR',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(28,'MALCOM',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(29,'MELODIA',(SELECT id FROM hero_type WHERE full_name ='DRUID'),false,3,(SELECT id FROM spell WHERE full_name = 'FORTUNE'),(SELECT id FROM spell WHERE full_name = 'FORTUNE')),
(30,'GEM',(SELECT id FROM hero_type WHERE full_name ='DRUID'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'SUMMON_BOAT')),
(31,'ULAND',(SELECT id FROM hero_type WHERE full_name ='DRUID'),true,3,(SELECT id FROM spell WHERE full_name = 'CURE'),(SELECT id FROM spell WHERE full_name = 'CURE')),
(32,'FAFNER',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'NAGA'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(33,'IONA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,1,(SELECT id FROM creature WHERE full_name = 'GENIE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(34,'JOSEPHINE',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,1,(SELECT id FROM creature WHERE full_name = 'STONE_GOLEM'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(35,'NEELA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(36,'PIQUEDRAM',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'STONE_GARGOYLE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(37,'RISSA',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),false,6,1,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(38,'THANE',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,1,(SELECT id FROM creature WHERE full_name = 'GENIE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(39,'TOROSAR',(SELECT id FROM hero_type WHERE full_name ='ALCHEMIST'),true,10,5,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(40,'AINE',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,4,350,(SELECT id FROM spell WHERE full_name = 'CURSE')),
(41,'ASTRAL',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,3,(SELECT id FROM spell WHERE full_name = 'HYPNOTIZE'),(SELECT id FROM spell WHERE full_name = 'HYPNOTIZE')),
(42,'CYRA',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(43,'DAREMYTH',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,3,(SELECT id FROM spell WHERE full_name = 'FORTUNE'),(SELECT id FROM spell WHERE full_name = 'FORTUNE')),
(44,'HALON',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(45,'SERENA',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(46,'SOLMYR',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,3,(SELECT id FROM spell WHERE full_name = 'CHAIN_LIGHTNING'),(SELECT id FROM spell WHERE full_name = 'CHAIN_LIGHTNING')),
(47,'THEODORUS',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,1,(SELECT id FROM creature WHERE full_name = 'MAGE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(148,'DRACON',(SELECT id FROM hero_type WHERE full_name ='WIZARD'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'ENCHANTER_BONUS'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(48,'CALH',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,1,(SELECT id FROM creature WHERE full_name = 'GOG'),null),
(49,'FIONA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'HELL_HOUND'),null),
(50,'IGNATIUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,1,(SELECT id FROM creature WHERE full_name = 'IMP'),null),
(51,'MARIUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'DEMON'),null),
(52,'NYMUS',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'PIT_FIEND'),null),
(53,'OCTAVIA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,4,350,null),
(54,'PYRE',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,10,5,null),
(55,'RASHKA',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),false,1,(SELECT id FROM creature WHERE full_name = 'EFREET'),null),
(149,'XERON',(SELECT id FROM hero_type WHERE full_name ='DEMONIAC'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DEVIL_BONUS'),null),
(56,'ASH',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,3,(SELECT id FROM spell WHERE full_name = 'BLOODLUST'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(57,'AXSIS',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(58,'AYDEN',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'VIEW_EARTH')),
(59,'CALID',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,7,1,(SELECT id FROM spell WHERE full_name = 'HASTE')),
(60,'OLEMA',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),false,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(61,'XYRON',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,3,(SELECT id FROM spell WHERE full_name = 'INFERNO'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(62,'XARFAX',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,3,(SELECT id FROM spell WHERE full_name = 'FIREBALL'),(SELECT id FROM spell WHERE full_name = 'FIREBALL')),
(63,'ZYDAR',(SELECT id FROM hero_type WHERE full_name ='HERETIC'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(64,'CHARNA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'WIGHT'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(65,'CLAVIUS',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,4,350,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(66,'GALTHRAN',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'SKELETON'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(67,'ISRA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(68,'MOANDOR',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'LICH'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(69,'STRAKER',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'WALKING_DEAD'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(70,'TAMIKA',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),false,1,(SELECT id FROM creature WHERE full_name = 'BLACK_KNIGHT'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(71,'VOKIAL',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,1,(SELECT id FROM creature WHERE full_name = 'VAMPIRE'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(155,'LORD_HAART_DEATH_KNIGHT',(SELECT id FROM hero_type WHERE full_name ='DEATH_KNIGHT'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DEATH_KNIGHT_BONUS'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(72,'AISLINN',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER'),(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER')),
(73,'NAGASH',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,4,350,(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(74,'NIMBUS',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(75,'SANDRO',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(76,'SEPTIENNA',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'DEATH_RIPPLE'),(SELECT id FROM spell WHERE full_name = 'DEATH_RIPPLE')),
(77,'THANT',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),true,3,(SELECT id FROM spell WHERE full_name = 'ANIMATE_DEAD'),(SELECT id FROM spell WHERE full_name = 'ANIMATE_DEAD')),
(78,'VIDOMINA',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'),(SELECT id FROM spell WHERE full_name = 'CURSE')),
(79,'XSI',(SELECT id FROM hero_type WHERE full_name ='NECROMANCER'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(80,'AJIT',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'BEHOLDER'),null),
(81,'ARLACH',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,10,5,null),
(82,'DACE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'MINOTAUR'),null),
(83,'DAMACON',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,4,350,null),
(84,'GUNNAR',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),null),
(85,'LORELEI',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,1,(SELECT id FROM creature WHERE full_name = 'HARPY'),null),
(86,'SHAKTI',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),true,1,(SELECT id FROM creature WHERE full_name = 'TROGLODYTE'),null),
(87,'SYNCA',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,1,(SELECT id FROM creature WHERE full_name = 'MANTICORE'),null),
(150,'MUTARE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DRAGON_BONUS'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(151,'MUTARE_DRAKE',(SELECT id FROM hero_type WHERE full_name ='OVERLORD'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'DRAGON_BONUS'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(88,'ALAMAR',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'RESURRECTION'),(SELECT id FROM spell WHERE full_name = 'RESURRECTION')),
(89,'DARKSTORN',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(90,'DEEMER',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER'),(SELECT id FROM spell WHERE full_name = 'METEOR_SHOWER')),
(91,'GEON',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(92,'JAEGAR',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(93,'JEDDITE',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,3,(SELECT id FROM spell WHERE full_name = 'RESURRECTION'),(SELECT id FROM spell WHERE full_name = 'RESURRECTION')),
(94,'MALEKITH',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(95,'SEPHINROTH',(SELECT id FROM hero_type WHERE full_name ='WARLOCK'),false,5,1,(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(96,'CRAG_HACK',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),null),
(97,'GRETCHIN',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),false,1,(SELECT id FROM creature WHERE full_name = 'GOBLIN'),null),
(98,'GURNISSON',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,10,5,null),
(99,'JABARKAS',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'ORC'),null),
(100,'KRELLION',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),null),
(101,'SHIVA',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),false,1,(SELECT id FROM creature WHERE full_name = 'ROC'),null),
(102,'TYRAXOR',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'WOLF_RIDER'),null),
(103,'YOG',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'CYCLOPS'),null),
(152,'BORAGUS',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),null),
(153,'KILGOR',(SELECT id FROM hero_type WHERE full_name ='BARBARIAN'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'BEHEMOTH_BONUS'),null),
(104,'DESSA',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(105,'GIRD',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(106,'GUNDULA',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(107,'ORIS',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_AIR')),
(108,'SAURUG',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,8,1,(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(109,'TEREK',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(110,'VEY',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,1,(SELECT id FROM creature WHERE full_name = 'OGRE'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(111,'ZUBIN',(SELECT id FROM hero_type WHERE full_name ='BATTLE_MAGE'),true,3,(SELECT id FROM spell WHERE full_name = 'PRECISION'),(SELECT id FROM spell WHERE full_name = 'PRECISION')),
(112,'ALKIN',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'GORGON'),null),
(113,'BROGHILD',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'WYVERN'),null),
(114,'BRON',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'BASILISK'),null),
(115,'DRAKON',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'GNOLL'),null),
(116,'GERWULF',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,10,5,null),
(117,'KORBAC',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'SERPENT_FLY'),null),
(118,'TAZAR',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,0,(SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'),null),
(119,'WYSTAN',(SELECT id FROM hero_type WHERE full_name ='BEASTMASTER'),true,1,(SELECT id FROM creature WHERE full_name = 'LIZARDMAN'),null),
(120,'ANDRA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'),(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(121,'MERIST',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(122,'MIRLANDA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,3,(SELECT id FROM spell WHERE full_name = 'WEAKNESS'),(SELECT id FROM spell WHERE full_name = 'WEAKNESS')),
(123,'ROSIC',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(124,'STYG',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'),(SELECT id FROM spell WHERE full_name = 'SHIELD')),
(125,'TIVA',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(126,'VERDISH',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'),(SELECT id FROM spell WHERE full_name = 'PROTECTION_FROM_FIRE')),
(127,'VOY',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'),(SELECT id FROM spell WHERE full_name = 'SLOW')),
(154,'ADRIENNE',(SELECT id FROM hero_type WHERE full_name ='WITCH'),false,0,(SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'),(SELECT id FROM spell WHERE full_name = 'INFERNO')),
(128,'ERDAMON',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'EARTH_ELEMENTAL_BONUS'),null),
(129,'FIUR',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'FIRE_ELEMENTAL_BONUS'),null),
(130,'IGNISSA',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'FIRE_ELEMENTAL_BONUS'),null),
(131,'KALT',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'WATER_ELEMENTAL_BONUS'),null),
(132,'LACUS',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'WATER_ELEMENTAL_BONUS'),null),
(133,'MONERE',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),true,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'PSYCHIC_ELEMENTAL_BONUS'),null),
(134,'PASIS',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'PSYCHIC_ELEMENTAL_BONUS'),null),
(135,'THUNAR',(SELECT id FROM hero_type WHERE full_name ='PLANESWALKER'),false,2,(SELECT id FROM specific_creature_specialty WHERE full_name = 'EARTH_ELEMENTAL_BONUS'),null),
(136,'AENAIN',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,3,(SELECT id FROM spell WHERE full_name = 'DISRUPTING_RAY'),(SELECT id FROM spell WHERE full_name = 'DISRUPTING_RAY')),
(137,'BRISSA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'HASTE'),(SELECT id FROM spell WHERE full_name = 'HASTE')),
(138,'CIELE',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW'),(SELECT id FROM spell WHERE full_name = 'MAGIC_ARROW')),
(139,'GELARE',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,4,350,(SELECT id FROM spell WHERE full_name = 'DISPEL')),
(140,'GRINDAN',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,4,350,(SELECT id FROM spell WHERE full_name = 'SLOW')),
(141,'INTEUS',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),true,3,(SELECT id FROM spell WHERE full_name = 'BLOODLUST'),(SELECT id FROM spell WHERE full_name = 'BLOODLUST')),
(142,'LABETHA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'STONE_SKIN'),(SELECT id FROM spell WHERE full_name = 'STONE_SKIN')),
(143,'LUNA',(SELECT id FROM hero_type WHERE full_name ='ELEMENTALIST'),false,3,(SELECT id FROM spell WHERE full_name = 'FIRE_WALL'),(SELECT id FROM spell WHERE full_name = 'FIRE_WALL'));

create table hero_to_base_skill (
id serial primary key,
hero_id int4 not null,
sec_by_lvl_id int4 not null,
CONSTRAINT fk_hero FOREIGN KEY(hero_id) REFERENCES hero(id),
CONSTRAINT fk_skill FOREIGN KEY(sec_by_lvl_id) REFERENCES secondary_by_level(id));

insert into hero_to_base_skill (
hero_id, sec_by_lvl_id
) values
((SELECT id FROM hero WHERE full_name = 'CHRISTIAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'CHRISTIAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'EDRIC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'EDRIC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'ORRIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'ORRIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'SYLVIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'SYLVIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'))),
((SELECT id FROM hero WHERE full_name = 'VALESKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'VALESKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'SORSHA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'SORSHA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'TYRIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'TYRIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'CATHERINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'CATHERINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'ROLAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'ROLAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'SIR_MULLICH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'ADELA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ADELA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'))),
((SELECT id FROM hero WHERE full_name = 'ADELAIDE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CAITLIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CAITLIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'CUTHBERT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CUTHBERT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'INGHAM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'INGHAM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'LOYNIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'LOYNIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'RION'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'RION'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'))),
((SELECT id FROM hero WHERE full_name = 'SANYA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'SANYA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'JENOVA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'KYRRE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'KYRRE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'))),
((SELECT id FROM hero WHERE full_name = 'IVOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'IVOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'UFRETIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'UFRETIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LUCK'))),
((SELECT id FROM hero WHERE full_name = 'CLANCY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'CLANCY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'))),
((SELECT id FROM hero WHERE full_name = 'THORGRIM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'RYLAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'RYLAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'))),
((SELECT id FROM hero WHERE full_name = 'MEPHALA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'MEPHALA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'GELU'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'GELU'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'AERIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'AERIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'ALAGAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ALAGAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'CORONIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CORONIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'ELLESHAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ELLESHAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'MALCOM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'MALCOM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'MELODIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'MELODIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LUCK'))),
((SELECT id FROM hero WHERE full_name = 'GEM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GEM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'))),
((SELECT id FROM hero WHERE full_name = 'ULAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ULAND'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'))),
((SELECT id FROM hero WHERE full_name = 'FAFNER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'FAFNER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'IONA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'IONA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'JOSEPHINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'JOSEPHINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'NEELA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'NEELA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'PIQUEDRAM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'PIQUEDRAM'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'RISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'RISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'THANE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'TOROSAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'TOROSAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'AINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'AINE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'ASTRAL'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CYRA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CYRA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'))),
((SELECT id FROM hero WHERE full_name = 'DAREMYTH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'DAREMYTH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'HALON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'HALON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'SERENA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'SERENA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'SOLMYR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'SOLMYR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'THEODORUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'THEODORUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'))),
((SELECT id FROM hero WHERE full_name = 'DRACON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CALH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'CALH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'FIONA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'IGNATIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'IGNATIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'MARIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'NYMUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'OCTAVIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'OCTAVIA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'PYRE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'))),
((SELECT id FROM hero WHERE full_name = 'PYRE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'RASHKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'RASHKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'XERON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'XERON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'ASH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ASH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'AXSIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'AXSIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'AYDEN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'AYDEN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'CALID'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CALID'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'OLEMA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'OLEMA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'))),
((SELECT id FROM hero WHERE full_name = 'XYRON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'XYRON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'XARFAX'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'XARFAX'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'ZYDAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ZYDAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'CHARNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'CHARNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'CLAVIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'CLAVIUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'GALTHRAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'GALTHRAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'ISRA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'MOANDOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'MOANDOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'STRAKER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'STRAKER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'TAMIKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'TAMIKA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'VOKIAL'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'VOKIAL'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'LORD_HAART_DEATH_KNIGHT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'AISLINN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'AISLINN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'NAGASH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'NAGASH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'NIMBUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'NIMBUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'SANDRO'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'SANDRO'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'SEPTIENNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'SEPTIENNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'THANT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'THANT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'VIDOMINA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'XSI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'))),
((SELECT id FROM hero WHERE full_name = 'XSI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'AJIT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'AJIT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'ARLACH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'ARLACH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'DACE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'DACE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'DAMACON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'GUNNAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'GUNNAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'))),
((SELECT id FROM hero WHERE full_name = 'LORELEI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'LORELEI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'SHAKTI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'SHAKTI'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'SYNCA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'SYNCA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'MUTARE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'MUTARE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'MUTARE_DRAKE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'MUTARE_DRAKE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'ALAMAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ALAMAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'))),
((SELECT id FROM hero WHERE full_name = 'DARKSTORN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'DARKSTORN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'DEEMER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'DEEMER'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'GEON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GEON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'JAEGAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'JAEGAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'JEDDITE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'MALEKITH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'MALEKITH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'SEPHINROTH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'SEPHINROTH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'CRAG_HACK'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'GRETCHIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'GRETCHIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'))),
((SELECT id FROM hero WHERE full_name = 'GURNISSON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'GURNISSON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'JABARKAS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'JABARKAS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'KRELLION'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'KRELLION'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'SHIVA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'SHIVA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'TYRAXOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'TYRAXOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'YOG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'YOG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'))),
((SELECT id FROM hero WHERE full_name = 'BORAGUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'BORAGUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'KILGOR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'DESSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'DESSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'))),
((SELECT id FROM hero WHERE full_name = 'GIRD'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GIRD'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'GUNDULA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GUNDULA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'ORIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ORIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'SAURUG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'SAURUG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'TEREK'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'TEREK'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'VEY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'VEY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'ZUBIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ZUBIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'ALKIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'ALKIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'BROGHILD'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'BROGHILD'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'))),
((SELECT id FROM hero WHERE full_name = 'BRON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'BRON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'))),
((SELECT id FROM hero WHERE full_name = 'DRAKON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'DRAKON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'))),
((SELECT id FROM hero WHERE full_name = 'GERWULF'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'GERWULF'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'KORBAC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'KORBAC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'))),
((SELECT id FROM hero WHERE full_name = 'TAZAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'WYSTAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'))),
((SELECT id FROM hero WHERE full_name = 'WYSTAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'))),
((SELECT id FROM hero WHERE full_name = 'ANDRA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ANDRA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'))),
((SELECT id FROM hero WHERE full_name = 'MERIST'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'MERIST'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'MIRLANDA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ROSIC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ROSIC'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'))),
((SELECT id FROM hero WHERE full_name = 'STYG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'STYG'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'))),
((SELECT id FROM hero WHERE full_name = 'TIVA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'TIVA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'))),
((SELECT id FROM hero WHERE full_name = 'VERDISH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'VERDISH'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'))),
((SELECT id FROM hero WHERE full_name = 'VOY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'VOY'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'))),
((SELECT id FROM hero WHERE full_name = 'ADRIENNE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'ADRIENNE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 3 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'ERDAMON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'ERDAMON'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'FIUR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'IGNISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'IGNISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'KALT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'KALT'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'))),
((SELECT id FROM hero WHERE full_name = 'LACUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 2 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'MONERE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'MONERE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'))),
((SELECT id FROM hero WHERE full_name = 'PASIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'))),
((SELECT id FROM hero WHERE full_name = 'PASIS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'))),
((SELECT id FROM hero WHERE full_name = 'THUNAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'))),
((SELECT id FROM hero WHERE full_name = 'THUNAR'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'))),
((SELECT id FROM hero WHERE full_name = 'AENAIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'AENAIN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'BRISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'BRISSA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'CIELE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'CIELE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'GELARE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GELARE'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'GRINDAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'GRINDAN'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'INTEUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'INTEUS'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'LABETHA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'LABETHA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'))),
((SELECT id FROM hero WHERE full_name = 'LUNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'))),
((SELECT id FROM hero WHERE full_name = 'LUNA'),(SELECT id FROM secondary_by_level WHERE skill_lvl = 1 AND skill_id = (SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC')));

CREATE TABLE public.creature_to_specific (
	id serial primary key,
	specialty_id int4 not null,
	creature_id int4 not null
);

INSERT INTO public.creature_to_specific (
    specialty_id, creature_id
) values
((select id from specific_creature_specialty where full_name = 'DEATH_KNIGHT_BONUS'), (select id from creature where full_name = 'BLACK_KNIGHT')),
((select id from specific_creature_specialty where full_name = 'DEATH_KNIGHT_BONUS'), (select id from creature where full_name = 'DREAD_KNIGHT')),
((select id from specific_creature_specialty where full_name = 'BEHEMOTH_BONUS'), (select id from creature where full_name = 'BEHEMOTH')),
((select id from specific_creature_specialty where full_name = 'BEHEMOTH_BONUS'), (select id from creature where full_name = 'ANCIENT_BEHEMOTH')),
((select id from specific_creature_specialty where full_name = 'EARTH_ELEMENTAL_BONUS'), (select id from creature where full_name = 'EARTH_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'EARTH_ELEMENTAL_BONUS'), (select id from creature where full_name = 'MAGMA_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'FIRE_ELEMENTAL_BONUS'), (select id from creature where full_name = 'FIRE_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'FIRE_ELEMENTAL_BONUS'), (select id from creature where full_name = 'ENERGY_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'WATER_ELEMENTAL_BONUS'), (select id from creature where full_name = 'WATER_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'WATER_ELEMENTAL_BONUS'), (select id from creature where full_name = 'ICE_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'PSYCHIC_ELEMENTAL_BONUS'), (select id from creature where full_name = 'PSYCHIC_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'PSYCHIC_ELEMENTAL_BONUS'), (select id from creature where full_name = 'MAGIC_ELEMENTAL')),
((select id from specific_creature_specialty where full_name = 'DEVIL_BONUS'), (select id from creature where full_name = 'DEVIL')),
((select id from specific_creature_specialty where full_name = 'DEVIL_BONUS'), (select id from creature where full_name = 'ARCH_DEVIL')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GREEN_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GOLD_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'RED_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'BLACK_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'BONE_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'GHOST_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'AZURE_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'CRYSTAL_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'RUST_DRAGON')),
((select id from specific_creature_specialty where full_name = 'DRAGON_BONUS'), (select id from creature where full_name = 'FAERIE_DRAGON'));

-- drop table hero_to_skill;
-- drop table hero;
-- drop table specific_creature_specialty;
-- drop table public.creature__to_specific;