create table secondary_skill (
id int4 not null primary key,
full_name varchar not null
);

-- drop table secondary_skill;

insert into secondary_skill (
id, full_name
) values
(0, 'ARCHERY'),
(1, 'OFFENSE'),
(2, 'ARMORER'),
(3, 'RESISTANCE'),
(4, 'LEADERSHIP'),
(5, 'LUCK'),
(6, 'TACTICS'),
(7, 'ARTILLERY'),
(8, 'BALLISTICS'),
(9, 'FIRST_AID'),
(10, 'NECROMANCY'),
(11, 'DIPLOMACY'),
(12, 'ESTATES'),
(13, 'LEARNING'),
(14, 'LOGISTICS'),
(15, 'PATHFINDING'),
(16, 'SCOUTING'),
(17, 'NAVIGATION'),
(18, 'EAGLE_EYE'),
(19, 'INTELLIGENCE'),
(20, 'MYSTICISM'),
(21, 'SCHOLAR'),
(22, 'SORCERY'),
(23, 'WISDOM'),
(24, 'AIR_MAGIC'),
(25, 'EARTH_MAGIC'),
(26, 'FIRE_MAGIC'),
(27, 'WATER_MAGIC');

create table secondary_by_level (
id serial primary key,
skill_id int4 not null,
skill_lvl int4 not null,
effect int4,
CONSTRAINT fk_skill FOREIGN KEY(skill_id) REFERENCES secondary_skill(id)
);

-- drop table secondary_by_level;

insert into secondary_by_level (
skill_id, skill_lvl, effect
) values
((SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'), 1, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'), 2, 25),
((SELECT id FROM secondary_skill WHERE full_name = 'ARCHERY'), 3, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'), 1, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'), 2, 20),
((SELECT id FROM secondary_skill WHERE full_name = 'OFFENSE'), 3, 30),
((SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'), 1, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'), 2, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'ARMORER'), 3, 15),
((SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'), 1, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'), 2, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'RESISTANCE'), 3, 20),
((SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'), 1, 1),
((SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'), 2, 2),
((SELECT id FROM secondary_skill WHERE full_name = 'LEADERSHIP'), 3, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'LUCK'), 1, 1),
((SELECT id FROM secondary_skill WHERE full_name = 'LUCK'), 2, 2),
((SELECT id FROM secondary_skill WHERE full_name = 'LUCK'), 3, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'), 1, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'), 2, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'TACTICS'), 3, 7),
((SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'), 1, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'), 2, 75),
((SELECT id FROM secondary_skill WHERE full_name = 'ARTILLERY'), 3, 100),
((SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'), 1, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'), 2, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'BALLISTICS'), 3, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'), 1, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'), 2, 75),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRST_AID'), 3, 100),
((SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'), 1, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'), 2, 20),
((SELECT id FROM secondary_skill WHERE full_name = 'NECROMANCY'), 3, 30),
((SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'), 1, 20),
((SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'), 2, 40),
((SELECT id FROM secondary_skill WHERE full_name = 'DIPLOMACY'), 3, 60),
((SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'), 1, 125),
((SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'), 2, 250),
((SELECT id FROM secondary_skill WHERE full_name = 'ESTATES'), 3, 500),
((SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'), 1, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'), 2, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'LEARNING'), 3, 15),
((SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'), 1, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'), 2, 20),
((SELECT id FROM secondary_skill WHERE full_name = 'LOGISTICS'), 3, 30),
((SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'), 1, 25),
((SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'), 2, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'PATHFINDING'), 3, 75),
((SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'), 1, 1),
((SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'), 2, 2),
((SELECT id FROM secondary_skill WHERE full_name = 'SCOUTING'), 3, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'), 1, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'), 2, 100),
((SELECT id FROM secondary_skill WHERE full_name = 'NAVIGATION'), 3, 150),
((SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'), 1, 40),
((SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'), 2, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'EAGLE_EYE'), 3, 60),
((SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'), 1, 25),
((SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'), 2, 50),
((SELECT id FROM secondary_skill WHERE full_name = 'INTELLIGENCE'), 3, 100),
((SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'), 1, 2),
((SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'), 2, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'MYSTICISM'), 3, 4),
((SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'), 1, 2),
((SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'), 2, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'SCHOLAR'), 3, 4),
((SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'), 1, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'), 2, 10),
((SELECT id FROM secondary_skill WHERE full_name = 'SORCERY'), 3, 15),
((SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'), 1, 3),
((SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'), 2, 4),
((SELECT id FROM secondary_skill WHERE full_name = 'WISDOM'), 3, 5),
((SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'), 1, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'), 2, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'AIR_MAGIC'), 3, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'), 1, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'), 2, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'EARTH_MAGIC'), 3, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'), 1, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'), 2, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'FIRE_MAGIC'), 3, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'), 1, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'), 2, NULL),
((SELECT id FROM secondary_skill WHERE full_name = 'WATER_MAGIC'), 3, NULL);