create table spell (
id int4 not null primary key,
full_name varchar not null,
lvl int2 not null,
school int4 not null,
combat boolean not null
);

-- drop table spell;

insert into spell (
	id, full_name, lvl, school, combat
) values
(0, 'MAGIC_ARROW', 1, 0, true),
(1, 'HASTE', 1, 1, true),
(2, 'BLOODLUST', 1, 3, true),
(3, 'PROTECTION_FROM_FIRE', 1, 3, true),
(4, 'CURSE', 1, 3, true),
(5, 'BLESS', 1, 4, true),
(6, 'PROTECTION_FROM_WATER', 1, 4, true),
(7, 'CURE', 1, 4, true),
(8, 'DISPEL', 1, 4, true),
(9, 'STONE_SKIN', 1, 2, true),
(10, 'SLOW', 1, 2, true),
(11, 'SHIELD', 1, 2, true),
(12, 'VIEW_AIR', 1, 1, false),
(13, 'SUMMON_BOAT', 1, 4, false),
(14, 'VIEW_EARTH', 1, 2, false),
(15, 'LIGHTNING_BOLT', 2, 1, true),
(16, 'PRECISION', 2, 1, true),
(17, 'PROTECTION_FROM_AIR', 2, 1, true),
(18, 'DISRUPTING_RAY', 2, 1, true),
(19, 'FORTUNE', 2, 1, true),
(20, 'FIRE_WALL', 2, 3, true),
(21, 'BLIND', 2, 3, true),
(22, 'ICE_BOLT', 2, 4, true),
(23, 'REMOVE_OBSTACLE', 2, 4, true),
(24, 'WEAKNESS', 2, 4, true),
(25, 'QUICKSAND', 2, 2, true),
(26, 'DEATH_RIPPLE', 2, 2, true),
(27, 'VISIONS', 2, 0, false),
(28, 'DISGUISE', 2, 1, false),
(29, 'SCUTTLE_BOAT', 2, 4, false),
(30, 'HYPNOTIZE', 3, 1, true),
(31, 'DESTROY_UNDEAD', 3, 1, true),
(32, 'AIR_SHIELD', 3, 1, true),
(33, 'FIREBALL', 3, 3, true),
(34, 'LAND_MINES', 3, 3, true),
(35, 'MISFORTUNE', 3, 3, true),
(36, 'FORGETFULNESS', 3, 4, true),
(37, 'FROST_RING', 3, 4, true),
(38, 'MIRTH', 3, 4, true),
(39, 'TELEPORT', 3, 4, true),
(40, 'ANTIMAGIC', 3, 2, true),
(41, 'PROTECTION_FROM_EARTH', 3, 2, true),
(42, 'EARTHQUAKE', 3, 2, true),
(43, 'ANIMATE_DEAD', 3, 2, true),
(44, 'FORCE_FIELD', 3, 2, true),
(45, 'COUNTERSTRIKE', 4, 1, true),
(46, 'CHAIN_LIGHTNING', 4, 1, true),
(47, 'INFERNO', 4, 3, true),
(48, 'ARMAGEDDON', 4, 3, true),
(49, 'FRENZY', 4, 3, true),
(50, 'BERSERK', 4, 3, true),
(51, 'SLAYER', 4, 3, true),
(52, 'FIRE_SHIELD', 4, 3, true),
(53, 'CLONE', 4, 4, true),
(54, 'PRAYER', 4, 4, true),
(55, 'RESURRECTION', 4, 2, true),
(56, 'METEOR_SHOWER', 4, 2, true),
(57, 'SORROW', 4, 2, true),
(58, 'WATER_WALK', 4, 4, false),
(59, 'TOWN_PORTAL', 4, 2, false),
(60, 'TITANS_LIGHTNING_BOLT', 5, 1, true),
(61, 'MAGIC_MIRROR', 5, 1, true),
(62, 'AIR_ELEMENTAL', 5, 1, true),
(63, 'FIRE_ELEMENTAL', 5, 3, true),
(64, 'SACRIFICE', 5, 3, true),
(65, 'WATER_ELEMENTAL', 5, 4, true),
(66, 'IMPLOSION', 5, 2, true),
(67, 'EARTH_ELEMENTAL', 5, 2, true),
(68, 'FLY', 5, 1, false),
(69, 'DIMENSION_DOOR', 5, 1, false);

create table spell_by_school (
id serial primary key,
spell_id int4 not null,
school_lvl int4 not null,
spell_cost int4 not null,
base_effect int4,
power_effect int4,
massive boolean not null,
target int4,
CONSTRAINT fk_spell FOREIGN KEY(spell_id) REFERENCES spell(id)
);

-- drop table spell_by_school;

insert into spell_by_school (
	spell_id, school_lvl, spell_cost, base_effect, power_effect, massive, target
) values
((select id from spell where full_name = 'MAGIC_ARROW'), 0, 5, 10, 10, false, 0),
((select id from spell where full_name = 'MAGIC_ARROW'), 1, 4, 10, 10, false, 0),
((select id from spell where full_name = 'MAGIC_ARROW'), 2, 4, 20, 10, false, 0),
((select id from spell where full_name = 'MAGIC_ARROW'), 3, 4, 30, 10, false, 0),
((select id from spell where full_name = 'HASTE'), 0, 6, 3, null, false, 1),
((select id from spell where full_name = 'HASTE'), 1, 5, 3, null, false, 1),
((select id from spell where full_name = 'HASTE'), 2, 5, 5, null, false, 1),
((select id from spell where full_name = 'HASTE'), 3, 5, 5, null, true, 1),
((select id from spell where full_name = 'BLOODLUST'), 0, 5, 3, null, false, 1),
((select id from spell where full_name = 'BLOODLUST'), 1, 4, 3, null, false, 1),
((select id from spell where full_name = 'BLOODLUST'), 2, 4, 6, null, false, 1),
((select id from spell where full_name = 'BLOODLUST'), 3, 4, 6, null, true, 1),
((select id from spell where full_name = 'PROTECTION_FROM_FIRE'), 0, 5, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_FIRE'), 1, 4, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_FIRE'), 2, 4, 50, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_FIRE'), 3, 4, 50, null, true, 1),
((select id from spell where full_name = 'CURSE'), 0, 6, 0, null, false, 0),
((select id from spell where full_name = 'CURSE'), 1, 5, 0, null, false, 0),
((select id from spell where full_name = 'CURSE'), 2, 5, 1, null, false, 0),
((select id from spell where full_name = 'CURSE'), 3, 5, 1, null, true, 0),
((select id from spell where full_name = 'BLESS'), 0, 5, 0, null, false, 1),
((select id from spell where full_name = 'BLESS'), 1, 4, 0, null, false, 1),
((select id from spell where full_name = 'BLESS'), 2, 4, 1, null, false, 1),
((select id from spell where full_name = 'BLESS'), 3, 4, 1, null, true, 1),
((select id from spell where full_name = 'PROTECTION_FROM_WATER'), 0, 5, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_WATER'), 1, 4, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_WATER'), 2, 4, 50, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_WATER'), 3, 4, 50, null, true, 1),
((select id from spell where full_name = 'CURE'), 0, 6, 10, 5, false, 1),
((select id from spell where full_name = 'CURE'), 1, 5, 10, 5, false, 1),
((select id from spell where full_name = 'CURE'), 2, 5, 20, 5, false, 1),
((select id from spell where full_name = 'CURE'), 3, 5, 30, 5, true, 1),
((select id from spell where full_name = 'DISPEL'), 0, 5, null, null, false, 1),
((select id from spell where full_name = 'DISPEL'), 1, 4, null, null, false, 1),
((select id from spell where full_name = 'DISPEL'), 2, 4, null, null, false, 2),
((select id from spell where full_name = 'DISPEL'), 3, 4, null, null, true, 2),
((select id from spell where full_name = 'STONE_SKIN'), 0, 5, 3, null, false, 1),
((select id from spell where full_name = 'STONE_SKIN'), 1, 4, 3, null, false, 1),
((select id from spell where full_name = 'STONE_SKIN'), 2, 4, 6, null, false, 1),
((select id from spell where full_name = 'STONE_SKIN'), 3, 4, 6, null, true, 1),
((select id from spell where full_name = 'SLOW'), 0, 6, 25, null, false, 0),
((select id from spell where full_name = 'SLOW'), 1, 5, 25, null, false, 0),
((select id from spell where full_name = 'SLOW'), 2, 5, 50, null, false, 0),
((select id from spell where full_name = 'SLOW'), 3, 5, 50, null, true, 0),
((select id from spell where full_name = 'SHIELD'), 0, 5, 15, null, false, 1),
((select id from spell where full_name = 'SHIELD'), 1, 4, 15, null, false, 1),
((select id from spell where full_name = 'SHIELD'), 2, 4, 30, null, false, 1),
((select id from spell where full_name = 'SHIELD'), 3, 4, 30, null, true, 1),
((select id from spell where full_name = 'VIEW_AIR'), 0, 2, null, null, false, null),
((select id from spell where full_name = 'VIEW_AIR'), 1, 1, null, null, false, null),
((select id from spell where full_name = 'VIEW_AIR'), 2, 1, null, null, false, null),
((select id from spell where full_name = 'VIEW_AIR'), 3, 1, null, null, false, null),
((select id from spell where full_name = 'SUMMON_BOAT'), 0, 8, 50, 0, false, null),
((select id from spell where full_name = 'SUMMON_BOAT'), 1, 7, 50, 0, false, null),
((select id from spell where full_name = 'SUMMON_BOAT'), 2, 7, 75, 1, false, null),
((select id from spell where full_name = 'SUMMON_BOAT'), 3, 7, 100, 1, false, null),
((select id from spell where full_name = 'VIEW_EARTH'), 0, 2, null, null, false, null),
((select id from spell where full_name = 'VIEW_EARTH'), 1, 1, null, null, false, null),
((select id from spell where full_name = 'VIEW_EARTH'), 2, 1, null, null, false, null),
((select id from spell where full_name = 'VIEW_EARTH'), 3, 1, null, null, false, null),
((select id from spell where full_name = 'LIGHTNING_BOLT'), 0, 10, 10, 25, false, 0),
((select id from spell where full_name = 'LIGHTNING_BOLT'), 1, 8, 10, 25, false, 0),
((select id from spell where full_name = 'LIGHTNING_BOLT'), 2, 8, 25, 25, false, 0),
((select id from spell where full_name = 'LIGHTNING_BOLT'), 3, 8, 50, 25, false, 0),
((select id from spell where full_name = 'PRECISION'), 0, 8, 3, null, false, 1),
((select id from spell where full_name = 'PRECISION'), 1, 6, 3, null, false, 1),
((select id from spell where full_name = 'PRECISION'), 2, 6, 6, null, false, 1),
((select id from spell where full_name = 'PRECISION'), 3, 6, 6, null, true, 1),
((select id from spell where full_name = 'PROTECTION_FROM_AIR'), 0, 7, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_AIR'), 1, 5, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_AIR'), 2, 5, 50, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_AIR'), 3, 5, 50, null, true, 1),
((select id from spell where full_name = 'DISRUPTING_RAY'), 0, 10, 3, null, false, 0),
((select id from spell where full_name = 'DISRUPTING_RAY'), 1, 8, 3, null, false, 0),
((select id from spell where full_name = 'DISRUPTING_RAY'), 2, 8, 4, null, false, 0),
((select id from spell where full_name = 'DISRUPTING_RAY'), 3, 8, 5, null, false, 0),
((select id from spell where full_name = 'FORTUNE'), 0, 7, 1, null, false, 1),
((select id from spell where full_name = 'FORTUNE'), 1, 5, 1, null, false, 1),
((select id from spell where full_name = 'FORTUNE'), 2, 5, 2, null, false, 1),
((select id from spell where full_name = 'FORTUNE'), 3, 5, 2, null, true, 1),
((select id from spell where full_name = 'FIRE_WALL'), 0, 8, 10, 10, false, 3),
((select id from spell where full_name = 'FIRE_WALL'), 1, 6, 10, 10, false, 3),
((select id from spell where full_name = 'FIRE_WALL'), 2, 6, 20, 10, false, 3),
((select id from spell where full_name = 'FIRE_WALL'), 3, 6, 50, 10, false, 3),
((select id from spell where full_name = 'BLIND'), 0, 8, 50, null, false, 0),
((select id from spell where full_name = 'BLIND'), 1, 6, 50, null, false, 0),
((select id from spell where full_name = 'BLIND'), 2, 6, 25, null, false, 0),
((select id from spell where full_name = 'BLIND'), 3, 6, 0, null, false, 0),
((select id from spell where full_name = 'ICE_BOLT'), 0, 8, 10, 20, false, 0),
((select id from spell where full_name = 'ICE_BOLT'), 1, 6, 10, 20, false, 0),
((select id from spell where full_name = 'ICE_BOLT'), 2, 6, 20, 20, false, 0),
((select id from spell where full_name = 'ICE_BOLT'), 3, 6, 50, 20, false, 0),
((select id from spell where full_name = 'REMOVE_OBSTACLE'), 0, 7, null, null, false, 3),
((select id from spell where full_name = 'REMOVE_OBSTACLE'), 1, 5, null, null, false, 3),
((select id from spell where full_name = 'REMOVE_OBSTACLE'), 2, 5, null, null, false, 3),
((select id from spell where full_name = 'REMOVE_OBSTACLE'), 3, 5, null, null, false, 3),
((select id from spell where full_name = 'WEAKNESS'), 0, 8, 0, null, false, 0),
((select id from spell where full_name = 'WEAKNESS'), 1, 6, 3, null, false, 0),
((select id from spell where full_name = 'WEAKNESS'), 2, 6, 6, null, false, 0),
((select id from spell where full_name = 'WEAKNESS'), 3, 6, 6, null, true, 0),
((select id from spell where full_name = 'QUICKSAND'), 0, 8, 4, null, true, 3),
((select id from spell where full_name = 'QUICKSAND'), 1, 6, 4, null, true, 3),
((select id from spell where full_name = 'QUICKSAND'), 2, 6, 6, null, true, 3),
((select id from spell where full_name = 'QUICKSAND'), 3, 6, 8, null, true, 3),
((select id from spell where full_name = 'DEATH_RIPPLE'), 0, 10, 10, 5, true, 2),
((select id from spell where full_name = 'DEATH_RIPPLE'), 1, 8, 10, 5, true, 2),
((select id from spell where full_name = 'DEATH_RIPPLE'), 2, 8, 20, 5, true, 2),
((select id from spell where full_name = 'DEATH_RIPPLE'), 3, 8, 30, 5, true, 2),
((select id from spell where full_name = 'VISIONS'), 0, 4, null, 1, false, null),
((select id from spell where full_name = 'VISIONS'), 1, 2, null, 1, false, null),
((select id from spell where full_name = 'VISIONS'), 2, 2, null, 2, false, null),
((select id from spell where full_name = 'VISIONS'), 3, 2, null, 3, false, null),
((select id from spell where full_name = 'DISGUISE'), 0, 4, null, null, false, null),
((select id from spell where full_name = 'DISGUISE'), 1, 2, null, null, false, null),
((select id from spell where full_name = 'DISGUISE'), 2, 2, null, null, false, null),
((select id from spell where full_name = 'DISGUISE'), 3, 2, null, null, false, null),
((select id from spell where full_name = 'SCUTTLE_BOAT'), 0, 8, null, null, false, null),
((select id from spell where full_name = 'SCUTTLE_BOAT'), 1, 6, null, null, false, null),
((select id from spell where full_name = 'SCUTTLE_BOAT'), 2, 6, null, null, false, null),
((select id from spell where full_name = 'SCUTTLE_BOAT'), 3, 6, null, null, false, null),
((select id from spell where full_name = 'HYPNOTIZE'), 0, 18, 10, 25, false, 0),
((select id from spell where full_name = 'HYPNOTIZE'), 1, 15, 10, 25, false, 0),
((select id from spell where full_name = 'HYPNOTIZE'), 2, 15, 25, 25, false, 0),
((select id from spell where full_name = 'HYPNOTIZE'), 3, 15, 50, 25, false, 0),
((select id from spell where full_name = 'DESTROY_UNDEAD'), 0, 15, 10, 10, true, 2),
((select id from spell where full_name = 'DESTROY_UNDEAD'), 1, 12, 10, 10, true, 2),
((select id from spell where full_name = 'DESTROY_UNDEAD'), 2, 12, 20, 10, true, 2),
((select id from spell where full_name = 'DESTROY_UNDEAD'), 3, 12, 50, 10, true, 2),
((select id from spell where full_name = 'AIR_SHIELD'), 0, 12, 25, null, false, 1),
((select id from spell where full_name = 'AIR_SHIELD'), 1, 9, 25, null, false, 1),
((select id from spell where full_name = 'AIR_SHIELD'), 2, 9, 50, null, false, 1),
((select id from spell where full_name = 'AIR_SHIELD'), 3, 9, 50, null, true, 1),
((select id from spell where full_name = 'FIREBALL'), 0, 15, 15, 10, false, 3),
((select id from spell where full_name = 'FIREBALL'), 1, 12, 15, 10, false, 3),
((select id from spell where full_name = 'FIREBALL'), 2, 12, 30, 10, false, 3),
((select id from spell where full_name = 'FIREBALL'), 3, 12, 60, 10, false, 3),
((select id from spell where full_name = 'LAND_MINES'), 0, 18, 25, 10, true, 3),
((select id from spell where full_name = 'LAND_MINES'), 1, 15, 25, 10, true, 3),
((select id from spell where full_name = 'LAND_MINES'), 2, 15, 25, 10, true, 3),
((select id from spell where full_name = 'LAND_MINES'), 3, 15, 100, 10, true, 3),
((select id from spell where full_name = 'MISFORTUNE'), 0, 12, 1, null, false, 0),
((select id from spell where full_name = 'MISFORTUNE'), 1, 9, 1, null, false, 0),
((select id from spell where full_name = 'MISFORTUNE'), 2, 9, 2, null, false, 0),
((select id from spell where full_name = 'MISFORTUNE'), 3, 9, 2, null, true, 0),
((select id from spell where full_name = 'FORGETFULNESS'), 0, 12, 50, null, false, 0),
((select id from spell where full_name = 'FORGETFULNESS'), 1, 9, 50, null, false, 0),
((select id from spell where full_name = 'FORGETFULNESS'), 2, 9, 0, null, false, 0),
((select id from spell where full_name = 'FORGETFULNESS'), 3, 9, 0, null, true, 0),
((select id from spell where full_name = 'FROST_RING'), 0, 12, 15, 10, false, 3),
((select id from spell where full_name = 'FROST_RING'), 1, 9, 15, 10, false, 3),
((select id from spell where full_name = 'FROST_RING'), 2, 9, 30, 10, false, 3),
((select id from spell where full_name = 'FROST_RING'), 3, 9, 60, 10, false, 3),
((select id from spell where full_name = 'MIRTH'), 0, 12, 1, null, false, 1),
((select id from spell where full_name = 'MIRTH'), 1, 9, 1, null, false, 1),
((select id from spell where full_name = 'MIRTH'), 2, 9, 2, null, false, 1),
((select id from spell where full_name = 'MIRTH'), 3, 9, 2, null, true, 1),
((select id from spell where full_name = 'TELEPORT'), 0, 15, null, null, false, 0),
((select id from spell where full_name = 'TELEPORT'), 1, 12, null, null, false, 0),
((select id from spell where full_name = 'TELEPORT'), 2, 6, null, null, false, 0),
((select id from spell where full_name = 'TELEPORT'), 3, 3, null, null, false, 0),
((select id from spell where full_name = 'ANTIMAGIC'), 0, 15, 3, null, false, 1),
((select id from spell where full_name = 'ANTIMAGIC'), 1, 12, 3, null, false, 1),
((select id from spell where full_name = 'ANTIMAGIC'), 2, 12, 4, null, false, 1),
((select id from spell where full_name = 'ANTIMAGIC'), 3, 12, 5, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_EARTH'), 0, 12, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_EARTH'), 1, 9, 30, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_EARTH'), 2, 9, 50, null, false, 1),
((select id from spell where full_name = 'PROTECTION_FROM_EARTH'), 3, 9, 50, null, true, 1),
((select id from spell where full_name = 'EARTHQUAKE'), 0, 20, 2, null, true, 0),
((select id from spell where full_name = 'EARTHQUAKE'), 1, 17, 2, null, true, 0),
((select id from spell where full_name = 'EARTHQUAKE'), 2, 17, 3, null, true, 0),
((select id from spell where full_name = 'EARTHQUAKE'), 3, 17, 4, null, true, 0),
((select id from spell where full_name = 'ANIMATE_DEAD'), 0, 15, 30, 50, false, 1),
((select id from spell where full_name = 'ANIMATE_DEAD'), 1, 12, 30, 50, false, 1),
((select id from spell where full_name = 'ANIMATE_DEAD'), 2, 12, 60, 50, false, 1),
((select id from spell where full_name = 'ANIMATE_DEAD'), 3, 12, 160, 50, false, 1),
((select id from spell where full_name = 'FORCE_FIELD'), 0, 12, null, null, false, 3),
((select id from spell where full_name = 'FORCE_FIELD'), 1, 9, null, null, false, 3),
((select id from spell where full_name = 'FORCE_FIELD'), 2, 9, null, null, false, 3),
((select id from spell where full_name = 'FORCE_FIELD'), 3, 9, null, null, false, 3),
((select id from spell where full_name = 'COUNTERSTRIKE'), 0, 24, 1, null, false, 1),
((select id from spell where full_name = 'COUNTERSTRIKE'), 1, 20, 1, null, false, 1),
((select id from spell where full_name = 'COUNTERSTRIKE'), 2, 20, 2, null, false, 1),
((select id from spell where full_name = 'COUNTERSTRIKE'), 3, 20, 99, null, true, 1),
((select id from spell where full_name = 'CHAIN_LIGHTNING'), 0, 24, 25, 40, false, 0),
((select id from spell where full_name = 'CHAIN_LIGHTNING'), 1, 20, 25, 40, false, 0),
((select id from spell where full_name = 'CHAIN_LIGHTNING'), 2, 20, 50, 40, false, 0),
((select id from spell where full_name = 'CHAIN_LIGHTNING'), 3, 20, 100, 40, false, 0),
((select id from spell where full_name = 'INFERNO'), 0, 16, 20, 10, false, 3),
((select id from spell where full_name = 'INFERNO'), 1, 12, 20, 10, false, 3),
((select id from spell where full_name = 'INFERNO'), 2, 12, 40, 10, false, 3),
((select id from spell where full_name = 'INFERNO'), 3, 12, 80, 10, false, 3),
((select id from spell where full_name = 'ARMAGEDDON'), 0, 24, 30, 50, true, 2),
((select id from spell where full_name = 'ARMAGEDDON'), 1, 20, 30, 50, true, 2),
((select id from spell where full_name = 'ARMAGEDDON'), 2, 20, 60, 50, true, 2),
((select id from spell where full_name = 'ARMAGEDDON'), 3, 20, 120, 50, true, 2),
((select id from spell where full_name = 'FRENZY'), 0, 16, 100, null, false, 1),
((select id from spell where full_name = 'FRENZY'), 1, 12, 100, null, false, 1),
((select id from spell where full_name = 'FRENZY'), 2, 12, 150, null, false, 1),
((select id from spell where full_name = 'FRENZY'), 3, 12, 200, null, false, 1),
((select id from spell where full_name = 'BERSERK'), 0, 20, 1, null, false, 3),
((select id from spell where full_name = 'BERSERK'), 1, 16, 1, null, false, 3),
((select id from spell where full_name = 'BERSERK'), 2, 16, 2, null, false, 3),
((select id from spell where full_name = 'BERSERK'), 3, 16, 3, null, false, 3),
((select id from spell where full_name = 'SLAYER'), 0, 16, 8, null, false, 1),
((select id from spell where full_name = 'SLAYER'), 1, 12, 8, null, false, 1),
((select id from spell where full_name = 'SLAYER'), 2, 12, 8, null, false, 1),
((select id from spell where full_name = 'SLAYER'), 3, 12, 8, null, false, 1),
((select id from spell where full_name = 'FIRE_SHIELD'), 0, 16, 20, null, false, 1),
((select id from spell where full_name = 'FIRE_SHIELD'), 1, 12, 20, null, false, 1),
((select id from spell where full_name = 'FIRE_SHIELD'), 2, 12, 25, null, false, 1),
((select id from spell where full_name = 'FIRE_SHIELD'), 3, 12, 30, null, false, 1),
((select id from spell where full_name = 'CLONE'), 0, 24, 5, null, false, 1),
((select id from spell where full_name = 'CLONE'), 1, 20, 5, null, false, 1),
((select id from spell where full_name = 'CLONE'), 2, 20, 6, null, false, 1),
((select id from spell where full_name = 'CLONE'), 3, 20, 7, null, false, 1),
((select id from spell where full_name = 'PRAYER'), 0, 16, 2, null, false, 1),
((select id from spell where full_name = 'PRAYER'), 1, 12, 2, null, false, 1),
((select id from spell where full_name = 'PRAYER'), 2, 12, 4, null, false, 1),
((select id from spell where full_name = 'PRAYER'), 3, 12, 4, null, true, 1),
((select id from spell where full_name = 'RESURRECTION'), 0, 20, 40, 50, false, 1),
((select id from spell where full_name = 'RESURRECTION'), 1, 16, 40, 50, false, 1),
((select id from spell where full_name = 'RESURRECTION'), 2, 16, 80, 50, false, 1),
((select id from spell where full_name = 'RESURRECTION'), 3, 16, 160, 50, false, 1),
((select id from spell where full_name = 'METEOR_SHOWER'), 0, 16, 25, 25, false, 3),
((select id from spell where full_name = 'METEOR_SHOWER'), 1, 12, 25, 25, false, 3),
((select id from spell where full_name = 'METEOR_SHOWER'), 2, 12, 50, 25, false, 3),
((select id from spell where full_name = 'METEOR_SHOWER'), 3, 12, 100, 25, false, 3),
((select id from spell where full_name = 'SORROW'), 0, 16, 1, null, false, 0),
((select id from spell where full_name = 'SORROW'), 1, 12, 1, null, false, 0),
((select id from spell where full_name = 'SORROW'), 2, 12, 2, null, false, 0),
((select id from spell where full_name = 'SORROW'), 3, 12, 2, null, true, 0),
((select id from spell where full_name = 'WATER_WALK'), 0, 12, 140, null, false, null),
((select id from spell where full_name = 'WATER_WALK'), 1, 8, 140, null, false, null),
((select id from spell where full_name = 'WATER_WALK'), 2, 8, 120, null, false, null),
((select id from spell where full_name = 'WATER_WALK'), 3, 8, 100, null, false, null),
((select id from spell where full_name = 'TOWN_PORTAL'), 0, 16, 300, null, false, null),
((select id from spell where full_name = 'TOWN_PORTAL'), 1, 12, 300, null, false, null),
((select id from spell where full_name = 'TOWN_PORTAL'), 2, 12, 300, null, false, null),
((select id from spell where full_name = 'TOWN_PORTAL'), 3, 12, 200, null, false, null),
((select id from spell where full_name = 'TITANS_LIGHTNING_BOLT'), 0, 0, 600, 0, false, 0),
((select id from spell where full_name = 'TITANS_LIGHTNING_BOLT'), 1, 0, 600, 0, false, 0),
((select id from spell where full_name = 'TITANS_LIGHTNING_BOLT'), 2, 0, 600, 0, false, 0),
((select id from spell where full_name = 'TITANS_LIGHTNING_BOLT'), 3, 0, 600, 0, false, 0),
((select id from spell where full_name = 'MAGIC_MIRROR'), 0, 25, 20, null, false, 1),
((select id from spell where full_name = 'MAGIC_MIRROR'), 1, 20, 20, null, false, 1),
((select id from spell where full_name = 'MAGIC_MIRROR'), 2, 20, 30, null, false, 1),
((select id from spell where full_name = 'MAGIC_MIRROR'), 3, 20, 40, null, false, 1),
((select id from spell where full_name = 'AIR_ELEMENTAL'), 0, 25, 0, 2, false, 3),
((select id from spell where full_name = 'AIR_ELEMENTAL'), 1, 20, 0, 2, false, 3),
((select id from spell where full_name = 'AIR_ELEMENTAL'), 2, 20, 0, 3, false, 3),
((select id from spell where full_name = 'AIR_ELEMENTAL'), 3, 20, 0, 4, false, 3),
((select id from spell where full_name = 'FIRE_ELEMENTAL'), 0, 25, 0, 2, false, 3),
((select id from spell where full_name = 'FIRE_ELEMENTAL'), 1, 20, 0, 2, false, 3),
((select id from spell where full_name = 'FIRE_ELEMENTAL'), 2, 20, 0, 3, false, 3),
((select id from spell where full_name = 'FIRE_ELEMENTAL'), 3, 20, 0, 4, false, 3),
((select id from spell where full_name = 'SACRIFICE'), 0, 25, 3, 1, false, 1),
((select id from spell where full_name = 'SACRIFICE'), 1, 20, 3, 1, false, 1),
((select id from spell where full_name = 'SACRIFICE'), 2, 20, 6, 1, false, 1),
((select id from spell where full_name = 'SACRIFICE'), 3, 20, 10, 1, false, 1),
((select id from spell where full_name = 'WATER_ELEMENTAL'), 0, 25, 0, 2, false, 3),
((select id from spell where full_name = 'WATER_ELEMENTAL'), 1, 20, 0, 2, false, 3),
((select id from spell where full_name = 'WATER_ELEMENTAL'), 2, 20, 0, 3, false, 3),
((select id from spell where full_name = 'WATER_ELEMENTAL'), 3, 20, 0, 4, false, 3),
((select id from spell where full_name = 'IMPLOSION'), 0, 30, 100, 75, false, 0),
((select id from spell where full_name = 'IMPLOSION'), 1, 25, 100, 75, false, 0),
((select id from spell where full_name = 'IMPLOSION'), 2, 25, 200, 75, false, 0),
((select id from spell where full_name = 'IMPLOSION'), 3, 25, 300, 75, false, 0),
((select id from spell where full_name = 'EARTH_ELEMENTAL'), 0, 25, 0, 2, false, 3),
((select id from spell where full_name = 'EARTH_ELEMENTAL'), 1, 20, 0, 2, false, 3),
((select id from spell where full_name = 'EARTH_ELEMENTAL'), 2, 20, 0, 3, false, 3),
((select id from spell where full_name = 'EARTH_ELEMENTAL'), 3, 20, 0, 4, false, 3),
((select id from spell where full_name = 'FLY'), 0, 20, 140, null, false, null),
((select id from spell where full_name = 'FLY'), 1, 15, 140, null, false, null),
((select id from spell where full_name = 'FLY'), 2, 15, 120, null, false, null),
((select id from spell where full_name = 'FLY'), 3, 15, 100, null, false, null),
((select id from spell where full_name = 'DIMENSION_DOOR'), 0, 25, 300, 1, false, null),
((select id from spell where full_name = 'DIMENSION_DOOR'), 1, 20, 300, 2, false, null),
((select id from spell where full_name = 'DIMENSION_DOOR'), 2, 20, 300, 3, false, null),
((select id from spell where full_name = 'DIMENSION_DOOR'), 3, 20, 200, 4, false, null);

alter table public.spell_by_school
add column coeff int4;

update spell_by_school
set coeff = 2
where spell_id = (select id from spell where full_name = 'FIRE_WALL') and school_lvl = 0;
update spell_by_school
set coeff = 2
where spell_id = (select id from spell where full_name = 'FIRE_WALL') and school_lvl = 1;
update spell_by_school
set coeff = 3
where spell_id = (select id from spell where full_name = 'FIRE_WALL') and school_lvl = 2;
update spell_by_school
set coeff = 3
where spell_id = (select id from spell where full_name = 'FIRE_WALL') and school_lvl = 3;
update spell_by_school
set coeff = 2
where spell_id = (select id from spell where full_name = 'FORCE_FIELD') and school_lvl = 0;
update spell_by_school
set coeff = 2
where spell_id = (select id from spell where full_name = 'FORCE_FIELD') and school_lvl = 1;
update spell_by_school
set coeff = 3
where spell_id = (select id from spell where full_name = 'FORCE_FIELD') and school_lvl = 2;
update spell_by_school
set coeff = 3
where spell_id = (select id from spell where full_name = 'FORCE_FIELD') and school_lvl = 3;
update spell_by_school
set coeff = 4
where spell_id = (select id from spell where full_name = 'LAND_MINES') and school_lvl = 0;
update spell_by_school
set coeff = 4
where spell_id = (select id from spell where full_name = 'LAND_MINES') and school_lvl = 1;
update spell_by_school
set coeff = 6
where spell_id = (select id from spell where full_name = 'LAND_MINES') and school_lvl = 2;
update spell_by_school
set coeff = 8
where spell_id = (select id from spell where full_name = 'LAND_MINES') and school_lvl = 3;
update spell_by_school
set coeff = 4
where spell_id = (select id from spell where full_name = 'CHAIN_LIGHTNING') and school_lvl = 0;
update spell_by_school
set coeff = 4
where spell_id = (select id from spell where full_name = 'CHAIN_LIGHTNING') and school_lvl = 1;
update spell_by_school
set coeff = 5
where spell_id = (select id from spell where full_name = 'CHAIN_LIGHTNING') and school_lvl = 2;
update spell_by_school
set coeff = 5
where spell_id = (select id from spell where full_name = 'CHAIN_LIGHTNING') and school_lvl = 3;
update spell_by_school
set coeff = base_effect, base_effect = null
where spell_id in (select id from spell where full_name in ('HASTE', 'BLOODLUST', 'PROTECTION_FROM_FIRE',
'CURSE', 'BLESS', 'PROTECTION_FROM_WATER', 'STONE_SKIN', 'SLOW', 'SHIELD',
'PRECISION', 'PROTECTION_FROM_AIR', 'DISRUPTING_RAY', 'FORTUNE', 'BLIND', 'WEAKNESS', 'QUICKSAND',
'AIR_SHIELD', 'MISFORTUNE', 'FORGETFULNESS', 'MIRTH', 'ANTIMAGIC', 'PROTECTION_FROM_EARTH', 'EARTHQUAKE',
'COUNTERSTRIKE', 'BERSERK', 'SLAYER', 'FIRE_SHIELD', 'CLONE', 'PRAYER', 'SORROW', 'MAGIC_MIRROR'));