CREATE TABLE public.unit_count (
	id serial primary key,
	creature_id int4 NOT null,
	amount int4 NOT null,
	CONSTRAINT fk_creature FOREIGN KEY(creature_id) REFERENCES creature(id));

CREATE UNIQUE INDEX idx_creature_amount ON unit_count(creature_id, amount);

INSERT INTO public.unit_count (
    creature_id, amount
) values
((SELECT id FROM creature WHERE full_name = 'SKELETON'),10),
((SELECT id FROM creature WHERE full_name = 'SKELETON'),12),
((SELECT id FROM creature WHERE full_name = 'SKELETON'),13),
((SELECT id FROM creature WHERE full_name = 'SKELETON'),20),
((SELECT id FROM creature WHERE full_name = 'WALKING_DEAD'),10),
((SELECT id FROM creature WHERE full_name = 'WALKING_DEAD'),20),
((SELECT id FROM creature WHERE full_name = 'WIGHT'),2),
((SELECT id FROM creature WHERE full_name = 'WIGHT'),3),
((SELECT id FROM creature WHERE full_name = 'WIGHT'),5),
((SELECT id FROM creature WHERE full_name = 'WIGHT'),10),
((SELECT id FROM creature WHERE full_name = 'VAMPIRE'),5),
((SELECT id FROM creature WHERE full_name = 'VAMPIRE'),10),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS'),4),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS'),6),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS'),8),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS'),10),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS_KING'),4),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS_KING'),6),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS_KING'),8),
((SELECT id FROM creature WHERE full_name = 'CYCLOPS_KING'),10),
((SELECT id FROM creature WHERE full_name = 'WATER_ELEMENTAL'),4),
((SELECT id FROM creature WHERE full_name = 'WATER_ELEMENTAL'),6),
((SELECT id FROM creature WHERE full_name = 'WATER_ELEMENTAL'),8),
((SELECT id FROM creature WHERE full_name = 'WATER_ELEMENTAL'),12),
((SELECT id FROM creature WHERE full_name = 'DRAGON_FLY'),6),
((SELECT id FROM creature WHERE full_name = 'DRAGON_FLY'),9),
((SELECT id FROM creature WHERE full_name = 'DRAGON_FLY'),12),
((SELECT id FROM creature WHERE full_name = 'DRAGON_FLY'),18),
((SELECT id FROM creature WHERE full_name = 'GREEN_DRAGON'),8),
((SELECT id FROM creature WHERE full_name = 'RED_DRAGON'),5),
((SELECT id FROM creature WHERE full_name = 'RED_DRAGON'),6),
((SELECT id FROM creature WHERE full_name = 'RED_DRAGON'),7),
((SELECT id FROM creature WHERE full_name = 'GOLD_DRAGON'),2),
((SELECT id FROM creature WHERE full_name = 'GOLD_DRAGON'),3),
((SELECT id FROM creature WHERE full_name = 'GOLD_DRAGON'),4),
((SELECT id FROM creature WHERE full_name = 'GOLD_DRAGON'),6),
((SELECT id FROM creature WHERE full_name = 'BLACK_DRAGON'),1),
((SELECT id FROM creature WHERE full_name = 'BLACK_DRAGON'),2),
((SELECT id FROM creature WHERE full_name = 'BLACK_DRAGON'),3),
((SELECT id FROM creature WHERE full_name = 'BLACK_DRAGON'),5),
((SELECT id FROM creature WHERE full_name = 'DWARF'),10),
((SELECT id FROM creature WHERE full_name = 'DWARF'),15),
((SELECT id FROM creature WHERE full_name = 'DWARF'),20),
((SELECT id FROM creature WHERE full_name = 'DWARF'),30),
((SELECT id FROM creature WHERE full_name = 'BATTLE_DWARF'),10),
((SELECT id FROM creature WHERE full_name = 'BATTLE_DWARF'),15),
((SELECT id FROM creature WHERE full_name = 'BATTLE_DWARF'),20),
((SELECT id FROM creature WHERE full_name = 'BATTLE_DWARF'),30),
((SELECT id FROM creature WHERE full_name = 'GRIFFIN'),10),
((SELECT id FROM creature WHERE full_name = 'GRIFFIN'),20),
((SELECT id FROM creature WHERE full_name = 'GRIFFIN'),30),
((SELECT id FROM creature WHERE full_name = 'GRIFFIN'),40),
((SELECT id FROM creature WHERE full_name = 'ROYAL_GRIFFIN'),10),
((SELECT id FROM creature WHERE full_name = 'ROYAL_GRIFFIN'),20),
((SELECT id FROM creature WHERE full_name = 'ROYAL_GRIFFIN'),30),
((SELECT id FROM creature WHERE full_name = 'ROYAL_GRIFFIN'),40),
((SELECT id FROM creature WHERE full_name = 'IMP'),20),
((SELECT id FROM creature WHERE full_name = 'IMP'),30),
((SELECT id FROM creature WHERE full_name = 'IMP'),40),
((SELECT id FROM creature WHERE full_name = 'IMP'),60),
((SELECT id FROM creature WHERE full_name = 'FAMILIAR'),20),
((SELECT id FROM creature WHERE full_name = 'FAMILIAR'),30),
((SELECT id FROM creature WHERE full_name = 'FAMILIAR'),40),
((SELECT id FROM creature WHERE full_name = 'FAMILIAR'),60),
((SELECT id FROM creature WHERE full_name = 'MEDUSA'),4),
((SELECT id FROM creature WHERE full_name = 'MEDUSA'),6),
((SELECT id FROM creature WHERE full_name = 'MEDUSA'),8),
((SELECT id FROM creature WHERE full_name = 'MEDUSA'),10),
((SELECT id FROM creature WHERE full_name = 'MEDUSA_QUEEN'),4),
((SELECT id FROM creature WHERE full_name = 'MEDUSA_QUEEN'),6),
((SELECT id FROM creature WHERE full_name = 'MEDUSA_QUEEN'),8),
((SELECT id FROM creature WHERE full_name = 'MEDUSA_QUEEN'),10),
((SELECT id FROM creature WHERE full_name = 'NAGA'),2),
((SELECT id FROM creature WHERE full_name = 'NAGA'),3),
((SELECT id FROM creature WHERE full_name = 'NAGA'),4),
((SELECT id FROM creature WHERE full_name = 'NAGA'),6),
((SELECT id FROM creature WHERE full_name = 'NAGA_QUEEN'),2),
((SELECT id FROM creature WHERE full_name = 'NAGA_QUEEN'),3),
((SELECT id FROM creature WHERE full_name = 'NAGA_QUEEN'),4),
((SELECT id FROM creature WHERE full_name = 'NAGA_QUEEN'),6),
((SELECT id FROM creature WHERE full_name = 'WYVERN'),4),
((SELECT id FROM creature WHERE full_name = 'WYVERN'),6),
((SELECT id FROM creature WHERE full_name = 'WYVERN'),8),
((SELECT id FROM creature WHERE full_name = 'WYVERN'),12),
((SELECT id FROM creature WHERE full_name = 'ANGEL'),1),
((SELECT id FROM creature WHERE full_name = 'ANGEL'),2),
((SELECT id FROM creature WHERE full_name = 'ANGEL'),3),
((SELECT id FROM creature WHERE full_name = 'ANGEL'),4);

create table public.bank_option (
    id serial primary key,
    bank_id int4 not null,
    full_name varchar not null,
    probability int4 not null,
    CONSTRAINT fk_visiting_object FOREIGN KEY(bank_id) REFERENCES visiting_object_type(id)
);

INSERT INTO public.bank_option (
    bank_id, full_name, probability
) values
((SELECT id from visiting_object_type WHERE full_name = 'CRYPT'), 'MINI', 30),
((SELECT id from visiting_object_type WHERE full_name = 'CRYPT'), 'PREMINI', 30),
((SELECT id from visiting_object_type WHERE full_name = 'CRYPT'), 'PREMAXI', 30),
((SELECT id from visiting_object_type WHERE full_name = 'CRYPT'), 'MAXI', 10);

create table public.bank_to_unit (
    id serial primary key,
	unit_count_id int4 NOT null,
	option_id int4 NOT null,
	CONSTRAINT fk_unit_count FOREIGN KEY(unit_count_id) REFERENCES unit_count(id),
	CONSTRAINT fk_object FOREIGN KEY(option_id) REFERENCES bank_option(id)
);

INSERT INTO public.bank_to_unit (
    unit_count_id, option_id
) values
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 13),
(SELECT id from bank_option WHERE full_name = 'PREMINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'PREMINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WIGHT') and amount = 5),
(SELECT id from bank_option WHERE full_name = 'PREMINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'PREMINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 12),
(SELECT id from bank_option WHERE full_name = 'PREMINI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 20),
(SELECT id from bank_option WHERE full_name = 'PREMAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 20),
(SELECT id from bank_option WHERE full_name = 'PREMAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WIGHT') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'PREMAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'VAMPIRE') and amount = 5),
(SELECT id from bank_option WHERE full_name = 'PREMAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'SKELETON') and amount = 20),
(SELECT id from bank_option WHERE full_name = 'MAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WALKING_DEAD') and amount = 20),
(SELECT id from bank_option WHERE full_name = 'MAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'WIGHT') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT'))),
((SELECT id FROM unit_count WHERE creature_id = (SELECT id FROM creature WHERE full_name = 'VAMPIRE') and amount = 10),
(SELECT id from bank_option WHERE full_name = 'MAXI' and bank_id = (SELECT id from visiting_object_type WHERE full_name = 'CRYPT')));


