package ua.ihromant.sod.utils.map;

public enum SecondarySkill {
    ARCHERY, OFFENSE, ARMORER, RESISTANCE, LEADERSHIP, LUCK, TACTICS, ARTILLERY, BALLISTICS, FIRST_AID, // combat
    NECROMANCY, DIPLOMACY, ESTATES, LEARNING, LOGISTICS, PATHFINDING, SCOUTING, NAVIGATION, // adventure
    EAGLE_EYE, INTELLIGENCE, MYSTICISM, SCHOLAR, SORCERY, WISDOM, AIR_MAGIC, EARTH_MAGIC, FIRE_MAGIC, WATER_MAGIC // magic
}
