package ua.ihromant.sod.utils;

import ua.ihromant.sod.utils.map.SecondarySkill;

import static ua.ihromant.sod.utils.map.SecondarySkill.*;

public interface ObjectNumberConstants {
    String[] CREATURES = {"PIKEMAN", "HALBERDIER", "ARCHER", "MARKSMAN", "GRIFFIN", "ROYAL_GRIFFIN", "SWORDSMAN", "CRUSADER",
            "MONK", "ZEALOT", "CAVALIER", "CHAMPION", "ANGEL", "ARCHANGEL", "CENTAUR", "CENTAUR_CAPTAIN", "DWARF", "BATTLE_DWARF",
            "WOOD_ELF", "GRAND_ELF", "PEGASUS", "SILVER_PEGASUS", "DENDROID_GUARD", "DENDROID_SOLDIER", "UNICORN", "WAR_UNICORN",
            "GREEN_DRAGON", "GOLD_DRAGON", "GREMLIN", "MASTER_GREMLIN", "STONE_GARGOYLE", "OBSIDIAN_GARGOYLE", "STONE_GOLEM",
            "IRON_GOLEM", "MAGE", "ARCH_MAGE", "GENIE", "MASTER_GENIE", "NAGA", "NAGA_QUEEN", "GIANT", "TITAN", "IMP", "FAMILIAR",
            "GOG", "MAGOG", "HELL_HOUND", "CERBERUS", "DEMON", "HORNED_DEMON", "PIT_FIEND", "PIT_LORD", "EFREET", "EFREET_SULTAN",
            "DEVIL", "ARCH_DEVIL", "SKELETON", "SKELETON_WARRIOR", "WALKING_DEAD", "ZOMBIE", "WIGHT", "WRAITH", "VAMPIRE",
            "VAMPIRE_LORD", "LICH", "POWER_LICH", "BLACK_KNIGHT", "DREAD_KNIGHT", "BONE_DRAGON", "GHOST_DRAGON", "TROGLODYTE",
            "INFERNAL_TROGLODYTE", "HARPY", "HARPY_HAG", "BEHOLDER", "EVIL_EYE", "MEDUSA", "MEDUSA_QUEEN", "MINOTAUR",
            "MINOTAUR_KING", "MANTICORE", "SCORPICORE", "RED_DRAGON", "BLACK_DRAGON", "GOBLIN", "HOBGOBLIN", "WOLF_RIDER",
            "WOLF_RAIDER", "ORC", "ORC_CHIEFTAIN", "OGRE", "OGRE_MAGE", "ROC", "THUNDER_BIRD", "CYCLOPS", "CYCLOPS_KING", "BEHEMOTH",
            "ANCIENT_BEHEMOTH", "GNOLL", "GNOLL_MARAUDER", "LIZARDMAN", "LIZARD_WARRIOR", "GORGON", "MIGHTY_GORGON", "SERPENT_FLY",
            "DRAGON_FLY", "BASILISK", "GREATER_BASILISK", "WYVERN", "WYVERN_MONARCH", "HYDRA", "CHAOS_HYDRA", "AIR_ELEMENTAL",
            "EARTH_ELEMENTAL", "FIRE_ELEMENTAL", "WATER_ELEMENTAL", "GOLD_GOLEM", "DIAMOND_GOLEM", "PIXIE", "SPRITE",
            "PSYCHIC_ELEMENTAL", "MAGIC_ELEMENTAL", null, "ICE_ELEMENTAL", null, "MAGMA_ELEMENTAL", null, "STORM_ELEMENTAL", null,
            "ENERGY_ELEMENTAL", "FIREBIRD", "PHOENIX", "AZURE_DRAGON", "CRYSTAL_DRAGON", "FAERIE_DRAGON", "RUST_DRAGON", "ENCHANTER",
            "SHARPSHOOTER", "HALFLING", "PEASANT", "BOAR", "MUMMY", "NOMAD", "ROGUE", "TROLL"};

    String[] DWELLINGS = {"BASILISK_PIT", "BEHEMOTH_LAIR", "PILLAR_OF_EYES", "HALL_OF_DARKNESS", "DRAGON_VAULT", "TRAINING_GROUNDS",
                    "CENTAUR_STABLES", "ALTAR_OF_AIR", "PORTAL_OF_GLORY", "CYCLOPS_CAVE", "FORSAKEN_PALACE", "SERPENT_FLY_HIVE", "DWARF_COTTAGE",
                    "ALTAR_OF_EARTH", "FIRE_LAKE", "HOMESTEAD", "ALTAR_OF_FIRE", "PARAPET", "ALTAR_OF_WISHES", "WOLF_PEN", "GNOLL_HUT",
                    "GOBLIN_BARRACKS", "HALL_OF_SINS", "GORGON_LAIR", "DRAGON_CLIFFS", "GRIFFIN_TOWER", "HARPY_LOFT", "KENNELS", "HYDRA_POND",
                    "IMP_CRUCIBLE", "LIZARD_DEN", "MAGE_TOWER", "MANTICORE_LAIR", "CHAPEL_OF_STILLED_VOICES", "LABYRINTH", "MONASTERY",
                    "GOLDEN_PAVILION", "DEMON_GATE", "OGRE_FORT", "ORC_TOWER", "HELL_HOLE", "DRAGON_CAVE", "CLIFF_NEST", "WORKSHOP",
                    "CLOUD_TEMPLE", "DENDROID_ARCHES", "WARREN", "ALTAR_OF_WATER", "TOMB_OF_SOULS", "WYVERN_NEST", "ENCHANTED_SPRING",
                    "UNICORN_GLADE_LARGE", "MAUSOLEUM", "ESTATE", "CURSED_TEMPLE", "GRAVEYARD", "GUARDHOUSE", "ARCHERS_TOWER", "BARRACKS",
                    "MAGIC_LANTERN", "ALTAR_OF_THOUGHT", "PYRE", "FROZEN_CLIFFS", "CRYSTAL_CAVE", "MAGIC_FOREST", "SULFUROUS_LAIR",
                    "ENCHANTERS_HOLLOW", "TREETOP_TOWER", "UNICORN_GLADE", "ALTAR_OF_AIR_ALT", "ALTAR_OF_EARTH_ALT", "ALTAR_OF_FIRE_ALT", "ALTAR_OF_WATER_ALT",
                    "THATCHED_HUT", "HOVEL", "BOAR_GLEN", "TOMB_OF_CURSES", "NOMAD_TENT", "ROUGE_CAVERN", "TROLL_BRIDGE", null, null,
                    "ALTAR_OF_WATER_ALT", "FORSAKEN_PALACE"};

    SecondarySkill[] SECONDARY = {
                            PATHFINDING, ARCHERY, LOGISTICS, SCOUTING,
                            DIPLOMACY, NAVIGATION, LEADERSHIP, WISDOM,
                            MYSTICISM, LUCK, BALLISTICS, EAGLE_EYE,
                            NECROMANCY, ESTATES, FIRE_MAGIC, AIR_MAGIC,
                            WATER_MAGIC, EARTH_MAGIC, SCHOLAR, TACTICS,
                            ARTILLERY, LEARNING, OFFENSE, ARMORER,
                            INTELLIGENCE, SORCERY, RESISTANCE, FIRST_AID};


    String[] SPELLS = {"SUMMON_BOAT", "SCUTTLE_BOAT", "VISIONS", "VIEW_EARTH", "DISGUISE", "VIEW_AIR", "FLY", "WATER_WALK",
            "DIMENSION_DOOR", "TOWN_PORTAL", "QUICKSAND", "LAND_MINES", "FORCE_FIELD", "FIRE_WALL", "EARTHQUAKE",
            "MAGIC_ARROW", "ICE_BOLT", "LIGHTNING_BOLT", "IMPLOSION", "CHAIN_LIGHTNING", "FROST_RING", "FIREBALL",
            "INFERNO", "METEOR_SHOWER", "DEATH_RIPPLE", "DESTROY_UNDEAD", "DESTROY_UNDEAD", "SHIELD", "AIR_SHIELD",
            "FIRE_SHIELD", "PROTECTION_FROM_AIR", "PROTECTION_FROM_FIRE", "PROTECTION_FROM_WATER", "PROTECTION_FROM_EARTH",
            "ANTIMAGIC", "DISPEL", "MAGIC_MIRROR", "CURE", "RESURRECTION", "ANIMATE_DEAD", "SACRIFICE", "BLESS", "CURSE",
            "BLOODLUST", "PRECISION", "WEAKNESS", "STONE_SKIN", "DISRUPTING_RAY", "PRAYER", "MIRTH", "SORROW", "FORTUNE",
            "MISFORTUNE", "HASTE", "SLOW", "SLAYER", "FRENZY", "TITANS_LIGHTNING_BOLT", "COUNTERSTRIKE", "BERSERK",
            "HYPNOTIZE", "FORGETFULNESS", "BLIND", "TELEPORT", "REMOVE_OBSTACLE", "CLONE", "FIRE_ELEMENTAL",
            "EARTH_ELEMENTAL", "WATER_ELEMENTAL", "AIR_ELEMENTAL"};
}
